.TH "Achroma.AchromaAssetManager.AchromaDownloadToken" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.AchromaAssetManager.AchromaDownloadToken
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBbucket\fP"
.br
.ti -1c
.RI "string \fBgeneration\fP"
.br
.ti -1c
.RI "string \fBmetageneration\fP"
.br
.ti -1c
.RI "string \fBcontentType\fP"
.br
.ti -1c
.RI "string \fBtimeCreated\fP"
.br
.ti -1c
.RI "string \fBupdated\fP"
.br
.ti -1c
.RI "string \fBstorageClass\fP"
.br
.ti -1c
.RI "string \fBsize\fP"
.br
.ti -1c
.RI "string \fBmd5Hash\fP"
.br
.ti -1c
.RI "string \fBcontentEncoding\fP"
.br
.ti -1c
.RI "string \fBcontentDisposition\fP"
.br
.ti -1c
.RI "string \fBcrc32c\fP"
.br
.ti -1c
.RI "string \fBetag\fP"
.br
.ti -1c
.RI "string \fBdownloadTokens\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
