.TH "Achroma.FriendVisualizer" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.FriendVisualizer
.SH SYNOPSIS
.br
.PP
.PP
Inherits DevionGames\&.UIWidgets\&.DialogBox\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShow\fP (string id, UnityAction< int > result, params string[] buttons)"
.br
.ti -1c
.RI "void \fBAddFriends\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFriendCard\fP \fBcard\fP"
.br
.ti -1c
.RI "Image \fBlockImage\fP"
.br
.ti -1c
.RI "Image \fBimage\fP"
.br
.ti -1c
.RI "Button \fBfriendButton\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBUserId\fP\fC [set]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
