.TH "Achroma.UserMatchData" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.UserMatchData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUserMatchData\fP (int totalMatches, int totalWins, int totalChromaWins, int totalAchromWins, int totalPoints, int storyAchrometerTier, int achrometerTier)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtotalMatches\fP"
.br
.ti -1c
.RI "int \fBtotalWins\fP"
.br
.ti -1c
.RI "int \fBtotalChromaWins\fP"
.br
.ti -1c
.RI "int \fBtotalAchromWins\fP"
.br
.ti -1c
.RI "int \fBtotalPoints\fP"
.br
.ti -1c
.RI "int \fBstoryAchrometerTier\fP"
.br
.ti -1c
.RI "int \fBachrometerTier\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
