.TH "Achroma.Location" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.Location
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocation\fP (int id, string name, string spriteName, string story)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBspriteName\fP"
.br
.ti -1c
.RI "string \fBstory\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Achroma\&.Location\&.Location (int id, string name, string spriteName, string story)"

.PP
\fBParameters\fP
.RS 4
\fIid\fP 
.br
\fIname\fP The name of the location
.br
\fIspriteName\fP The name of the sprite file that will loaded on the story mode or companion mode
.br
\fIstory\fP Which story this location is related to
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
