.TH "Achroma.AchrometerTier" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.AchrometerTier
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAchrometerTier\fP (int fromPoints, int toPoints, int tier)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfromPoints\fP"
.br
.ti -1c
.RI "int \fBtoPoints\fP"
.br
.ti -1c
.RI "int \fBtier\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
