.TH "Achroma.CardCollectionItem" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.CardCollectionItem
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCardCollectionItem\fP (string id, string name, string rarity, string story, bool ar, string hero, int shards)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBId\fP"
.br
.ti -1c
.RI "string \fBName\fP"
.br
.ti -1c
.RI "string \fBRarity\fP"
.br
.ti -1c
.RI "string \fBStory\fP"
.br
.ti -1c
.RI "bool \fBAR\fP"
.br
.ti -1c
.RI "List< \fBCardCollectionItemCode\fP > \fBCodes\fP"
.br
.ti -1c
.RI "string \fBHero\fP"
.br
.ti -1c
.RI "int \fBShards\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
