.TH "Achroma.AchromaNewsItem" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.AchromaNewsItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetTitle\fP (string text)"
.br
.ti -1c
.RI "void \fBSetImage\fP (string url)"
.br
.ti -1c
.RI "void \fBSetUrl\fP (string url)"
.br
.ti -1c
.RI "void \fBGoToUrl\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBtitle\fP"
.br
.ti -1c
.RI "RawImage \fBbackgroundImage\fP"
.br
.ti -1c
.RI "string \fBurl\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
