.TH "Achroma.AchromaShardAttraction" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.AchromaShardAttraction
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddShard\fP (GameObject atom, Transform parent, float scale)"
.br
.ti -1c
.RI "void \fBAddShard\fP (GameObject atom, Transform parent)"
.br
.ti -1c
.RI "void \fBAddPoints\fP (int count)"
.br
.ti -1c
.RI "void \fBAddPointsWithDistance\fP (int count)"
.br
.ti -1c
.RI "void \fBAddPoints\fP (int count, float sourcePosition, float targetPosition, UnityAction result=null)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fB_atom\fP"
.br
.ti -1c
.RI "Color \fB_color\fP"
.br
.ti -1c
.RI "Vector3 \fBspawingPosition\fP"
.br
.ti -1c
.RI "Vector3 \fB_spacingDirection\fP"
.br
.ti -1c
.RI "float \fB_spacingBetweenAttractPoints\fP"
.br
.ti -1c
.RI "float \fB_scaleAttractPoints\fP"
.br
.ti -1c
.RI "int \fB_amountOfAtomsPerPoint\fP"
.br
.ti -1c
.RI "Vector2 \fB_shardScaleMinMax\fP"
.br
.ti -1c
.RI "float \fB_strengthOfAttraction\fP"
.br
.ti -1c
.RI "float \fB_maxMagnitude\fP"
.br
.ti -1c
.RI "float \fB_randomPosDistance\fP"
.br
.ti -1c
.RI "bool \fB_useGravity\fP"
.br
.ti -1c
.RI "Vector3 \fB_destinationPoint\fP"
.br
.ti -1c
.RI "float \fBselfDestructionTime\fP = 5\&.0f"
.br
.ti -1c
.RI "ParticleSystem \fBcollisionEffect\fP"
.br
.ti -1c
.RI "float \fBatomicScale\fP = 1\&.0f"
.br
.ti -1c
.RI "bool \fBShowCollisionEffect\fP = true"
.br
.ti -1c
.RI "float \fBtimeInterval\fP = 0\&.1f"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
