.TH "Achroma.AchromaErrorDescription" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.AchromaErrorDescription
.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Attribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAchromaErrorDescription\fP (int code, string description)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcode\fP"
.br
.ti -1c
.RI "string \fBdescription\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
