.TH "Achroma.AchromaStoryDependency" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.AchromaStoryDependency \- This is the component to be attached to any object that has sub-objects that can be activated/deactivated according to the user's avatar story Example: a Curdle Hill character will disable all objects in the 'components' array but will activate the components set with Curdle Hill flag\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdateComponents\fP ()"
.br
.RI "This method will run through all the components and will only activate components that has to do with the avatar story\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBStoryDependencyComponent\fP[] \fBcomponents\fP"
.br
.ti -1c
.RI "\fBUserData\fP \fBuser\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the component to be attached to any object that has sub-objects that can be activated/deactivated according to the user's avatar story Example: a Curdle Hill character will disable all objects in the 'components' array but will activate the components set with Curdle Hill flag\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
