.TH "Achroma.PowerUpTypeEnum" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.PowerUpTypeEnum
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBGetPowerUpTitle\fP (Enum value)"
.br
.ti -1c
.RI "static string \fBGetPowerUpDescription\fP (Enum value)"
.br
.ti -1c
.RI "static string \fBGetPowerUpSprite\fP (Enum value)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
