.TH "AchromaAPI.AchromaInstanceControl" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AchromaAPI.AchromaInstanceControl \- Singleton with methods to get data from the Control File\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static List< \fBAchromaFileStory\fP > \fBGetListOfChapters\fP ()"
.br
.RI "Returns the list of chapters\&. "
.in -1c
.SH "Detailed Description"
.PP 
Singleton with methods to get data from the Control File\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
