.TH "Achroma.RankingUser" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.RankingUser
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitialize\fP (int ranking, string userId, string name, int totalChromaWins, int totalAchromWins, int totalPoints, int storyAchrometer, int achrometer, int character)"
.br
.ti -1c
.RI "void \fBInitialize\fP (int ranking, string userId, string name, int storyAchrometer, int character)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TMP_Text \fBuserRanking\fP"
.br
.ti -1c
.RI "TMP_Text \fBuserName\fP"
.br
.ti -1c
.RI "TMP_Text \fBuserWins\fP"
.br
.ti -1c
.RI "TMP_Text \fBachrometerTier\fP"
.br
.ti -1c
.RI "GameObject \fBheroObject\fP"
.br
.ti -1c
.RI "Image \fBavatar\fP"
.br
.ti -1c
.RI "Image \fBbackground\fP"
.br
.ti -1c
.RI "GameObject \fBchromaBackground\fP"
.br
.ti -1c
.RI "GameObject \fBachromBackground\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
