.TH "Achroma.AchromaShopAvatarChapter" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.AchromaShopAvatarChapter
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetChapterText\fP (\fBAchromaFileStory\fP story)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBchapter\fP"
.br
.ti -1c
.RI "RectTransform \fBstoryTargetReference\fP"
.br
.ti -1c
.RI "List< Transform > \fBstories\fP = new List<Transform>()"
.br
.ti -1c
.RI "RectTransform \fBscrollViewContent\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
