.TH "AchromaAPI.AchromaInstanceAchievements" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AchromaAPI.AchromaInstanceAchievements \- Singleton responsible with the methods to trigger achievement events on the user's account\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBUpdateStartAdventureAchievement\fP ()"
.br
.RI "Adds the Start Adventure achievement\&. "
.ti -1c
.RI "static void \fBUpdateUseChromaFlareAchievement\fP ()"
.br
.RI "Adds the Use Chroma Flare achievement\&. "
.ti -1c
.RI "static void \fBUpdateUseChromaticShieldAchievement\fP ()"
.br
.RI "Adds the Use Chromatic Shield achievement\&. "
.ti -1c
.RI "static void \fBUpdateUseAchromSurgeAchievement\fP ()"
.br
.RI "Adds the Use Achrom Surge achievement\&. "
.ti -1c
.RI "static void \fBUpdateUseRevealAchievement\fP ()"
.br
.RI "Adds the Use Reveal Achievement\&. "
.ti -1c
.RI "static void \fBUpdateUseReviveAchievement\fP ()"
.br
.RI "Adds the Use Revive Achievement\&. "
.ti -1c
.RI "static void \fBUpdateUseTimeStepAchievement\fP ()"
.br
.RI "Adds the Use Revive Achievement\&. "
.ti -1c
.RI "static void \fBUpdateVonRuthroEnding\fP ()"
.br
.RI "Adds the Von Ruthro Ending achievement\&. "
.ti -1c
.RI "static void \fBUpdateMagusEliteEnding\fP ()"
.br
.RI "Adds the Magus Elite Ending achievement\&. "
.ti -1c
.RI "static void \fBUpdateOccultistsEnding\fP ()"
.br
.RI "Adds the Occultists Ending achievement\&. "
.ti -1c
.RI "static void \fBUpdateCollectAllRelicPowers\fP ()"
.br
.RI "Adds the Collect All Relics and Powers achievement\&. "
.in -1c
.SH "Detailed Description"
.PP 
Singleton responsible with the methods to trigger achievement events on the user's account\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
