.TH "AchromaFormField" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AchromaFormField
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBHideError\fP ()"
.br
.ti -1c
.RI "void \fBShowError\fP (string error)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TMP_InputField \fBinputField\fP"
.br
.ti -1c
.RI "Text \fBmessageText\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
