.TH "Achroma.LoginHistory" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.LoginHistory
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoginHistory\fP (string RowId, string UserId, System\&.DateTime Date)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBrowId\fP"
.br
.ti -1c
.RI "string \fBuser\fP"
.br
.ti -1c
.RI "System\&.DateTime \fBdateTime\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
