.TH "Achroma.AchromaFlippableCard" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.AchromaFlippableCard
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBAchroma\&.FriendCard\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBFlipCardState\fP { \fBFront\fP, \fBBack\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBResetToFront\fP ()"
.br
.ti -1c
.RI "void \fBFlipCard\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FlipCardState \fBflipCardState\fP = FlipCardState\&.Front"
.br
.ti -1c
.RI "GameObject \fBfrontCard\fP"
.br
.ti -1c
.RI "UnityEvent \fBOnFlipFront\fP"
.br
.ti -1c
.RI "GameObject \fBbackCard\fP"
.br
.ti -1c
.RI "UnityEvent \fBOnFlipBack\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
