.TH "Achroma.PowerUpTypeDescriptiopn" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.PowerUpTypeDescriptiopn
.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Attribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPowerUpTypeDescriptiopn\fP (int id, string title, string description, string sprite)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "string \fBtitle\fP"
.br
.ti -1c
.RI "string \fBdescription\fP"
.br
.ti -1c
.RI "string \fBsprite\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
