.TH "AchromaAPI.AchromaInstanceSounds.AchromaSoundEffectDescription" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AchromaAPI.AchromaInstanceSounds.AchromaSoundEffectDescription
.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Attribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAchromaSoundEffectDescription\fP (string fileName, bool vibration)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBfileName\fP"
.br
.ti -1c
.RI "bool \fBvibration\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
