.TH "Achroma.RankingUserComparer" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.RankingUserComparer
.SH SYNOPSIS
.br
.PP
.PP
Inherits IComparer< IDictionary >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBCompare\fP (IDictionary x, IDictionary y)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
