.TH "Achroma.RemoteConfigManager" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.RemoteConfigManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRemoteConfigManager\fP ()"
.br
.RI "Initializer that creates the variable array\&. "
.ti -1c
.RI "string \fBGetString\fP (RemoteConfigVariableType varName)"
.br
.RI "Returns the string name of a Remote Config\&. The name may vary according to the platfrom\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRemoteConfigVariable\fP[] \fBvariables\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBRemoteConfigManager\fP \fBInstance\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "string Achroma\&.RemoteConfigManager\&.GetString (RemoteConfigVariableType varName)"

.PP
Returns the string name of a Remote Config\&. The name may vary according to the platfrom\&. 
.PP
\fBParameters\fP
.RS 4
\fIvarName\fP The Remote Config variable
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
