.TH "Achroma.AchromaShardShopDialogBox" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.AchromaShardShopDialogBox
.SH SYNOPSIS
.br
.PP
.PP
Inherits DevionGames\&.UIWidgets\&.DialogBox\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShow\fP (string title, string text, string price, string hero, Sprite sprite, \fBAchromaShopCurrency\fP currency, UnityAction< int > result, UnityAction purchaseAction, bool maskable, params string[] buttons)"
.br
.ti -1c
.RI "override void \fBClose\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TMP_Text \fBtextMesh\fP"
.br
.ti -1c
.RI "Button \fBPurchaseButton\fP"
.br
.ti -1c
.RI "Image \fBitemImage\fP"
.br
.ti -1c
.RI "TMP_Text \fBpriceText\fP"
.br
.ti -1c
.RI "TMP_Text \fBheroText\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
