.TH "Achroma.CardCollectionItemCode" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.CardCollectionItemCode
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBCode\fP"
.br
.ti -1c
.RI "bool \fBUnlocked\fP"
.br
.ti -1c
.RI "string \fBOwner\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
