.TH "Achroma.Transaction" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.Transaction
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransaction\fP (string StoryStepId, System\&.DateTime Date, int Type, int \fBValue\fP)"
.br
.ti -1c
.RI "\fBTransaction\fP (string StoryStepId, System\&.DateTime Date, int Type, int \fBValue\fP, int Character)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBstoryStepId\fP"
.br
.ti -1c
.RI "string \fBdateTime\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBcharacter\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
