.TH "Achroma.AchromaFileStory" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.AchromaFileStory
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "int \fBchapter\fP"
.br
.ti -1c
.RI "\fBCharacterAvatar\fP[] \fBavatars\fP"
.br
.ti -1c
.RI "\fBAchromaItemType\fP[] \fBitems\fP"
.br
.ti -1c
.RI "\fBAchromaActionType\fP[] \fBactions\fP"
.br
.ti -1c
.RI "\fBLocation\fP[] \fBlocations\fP"
.br
.ti -1c
.RI "string \fBweaverStory\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
