.TH "Achroma.CardCollection" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.CardCollection
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCardIsAREnabled\fP (string cardId)"
.br
.ti -1c
.RI "bool \fBCardHasShardRewards\fP (string cardId)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBCardCollectionItem\fP > \fBItems\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
