.TH "Achroma.MatchPlayer" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.MatchPlayer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatchPlayer\fP (string id, string name, int character, int balance)"
.br
.ti -1c
.RI "bool \fBHaveIWon\fP (bool hero=false)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "int \fBcharacter\fP = \-1"
.br
.ti -1c
.RI "int \fBbalance\fP"
.br
.ti -1c
.RI "bool \fBleft\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBHaveILost\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
