.TH "Achroma.AchromaShopAvatarGrid" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.AchromaShopAvatarGrid
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLoadAvatars\fP (UnityAction callback)"
.br
.RI "Loads the avatars in the grid layout\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAchromaFileStory\fP \fBstory\fP"
.br
.ti -1c
.RI "\fBAchromaShopItem\fP \fBavatarItemPrefab\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
