.TH "AchromaAPI" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AchromaAPI
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAchromaInstance\fP"
.br
.RI "Main Singleton responsible for initializing the \fBAchroma\fP Instance, which will add the scenes needed as well as the objects required to connect to Firebase\&. "
.ti -1c
.RI "class \fBAchromaInstanceAchievements\fP"
.br
.RI "Singleton responsible with the methods to trigger achievement events on the user's account\&. "
.ti -1c
.RI "class \fBAchromaInstanceAssets\fP"
.br
.RI "Singleton with the methods to instantiate assets like Characters, Locations, Objects, Actions\&. "
.ti -1c
.RI "class \fBAchromaInstanceAuth\fP"
.br
.RI "Singleton to sign in to \fBAchroma\fP Database\&. "
.ti -1c
.RI "class \fBAchromaInstanceControl\fP"
.br
.RI "Singleton with methods to get data from the Control File\&. "
.ti -1c
.RI "class \fBAchromaInstanceDatabase\fP"
.br
.RI "Database Singleton responsible with all the tools to gather the relevant data from \fBAchroma\fP Database\&. "
.ti -1c
.RI "class \fBAchromaInstanceMatch\fP"
.br
.RI "Singleton with methods related to the Companion match\&. "
.ti -1c
.RI "class \fBAchromaInstanceShards\fP"
.br
.RI "Singleton with methods related to the shards animation, like gaining and losing\&. "
.ti -1c
.RI "class \fBAchromaInstanceStory\fP"
.br
.RI "Singleton with methods related to the Adventure Mode\&. "
.ti -1c
.RI "class \fBAchromaInstanceUI\fP"
.br
.RI "Singleton with standardized UI elements like messages, loading screens, etc\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
