.TH "AchromaAPI.AchromaInstanceSounds.AchromaSoundEffectEnum" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AchromaAPI.AchromaInstanceSounds.AchromaSoundEffectEnum
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBGetSoundEffectFileName\fP (AchromaSoundEffect sound)"
.br
.ti -1c
.RI "static bool \fBGetVibration\fP (AchromaSoundEffect sound)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
