.TH "Achroma.AchromaShardParticle" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.AchromaShardParticle
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fB_attractedTo\fP"
.br
.ti -1c
.RI "float \fB_strengthOfAttraction\fP"
.br
.ti -1c
.RI "float \fB_maxMagnitude\fP"
.br
.ti -1c
.RI "float \fBdistance\fP = 1\&.0f"
.br
.ti -1c
.RI "bool \fBfreeParticle\fP = false"
.br
.ti -1c
.RI "bool \fBselfDestruct\fP = false"
.br
.ti -1c
.RI "\fBAchromaShardAttraction\fP \fBattraction\fP"
.br
.ti -1c
.RI "float \fBselfDestructionTime\fP = 5\&.0f"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
