.TH "Achroma.RemoteConfigVariable" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.RemoteConfigVariable
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRemoteConfigVariable\fP (RemoteConfigVariableType id, string name)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RemoteConfigVariableType \fBid\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
