.TH "Achroma.AchromaControlFileType" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.AchromaControlFileType
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAchromaAssetBundleFile\fP[] \fBfiles\fP"
.br
.ti -1c
.RI "\fBAchromaFileStory\fP[] \fBstories\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
