.TH "Achroma.Value" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.Value
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValue\fP (string UserId, string Name, object Progress, bool Synchronized)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBuser\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "object \fBvalue\fP"
.br
.ti -1c
.RI "bool \fBsynchronized\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
