.TH "Achroma.FriendRequestData" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.FriendRequestData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBrequestingUser\fP"
.br
.ti -1c
.RI "string \fBrequestedUser\fP"
.br
.ti -1c
.RI "int \fBstatus\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
