.TH "Achroma.CharacterAvatar" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.CharacterAvatar
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCharacterAvatar\fP (int id, string name, string spriteName, string spriteBackgroundName, string[] cards, string story, int shards, int companionInitialYPosition, bool hidden, int avatarXPosition, int avatarYPosition, string hero)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBspriteName\fP"
.br
.ti -1c
.RI "string \fBspriteBackgroundName\fP"
.br
.ti -1c
.RI "string[] \fBcards\fP"
.br
.ti -1c
.RI "string \fBstory\fP"
.br
.ti -1c
.RI "int \fBshards\fP"
.br
.ti -1c
.RI "int \fBcompanionInitialYPosition\fP"
.br
.ti -1c
.RI "bool \fBhidden\fP"
.br
.ti -1c
.RI "int \fBavatarXPosition\fP"
.br
.ti -1c
.RI "int \fBavatarYPosition\fP"
.br
.ti -1c
.RI "string \fBhero\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Achroma\&.CharacterAvatar\&.CharacterAvatar (int id, string name, string spriteName, string spriteBackgroundName, string[] cards, string story, int shards, int companionInitialYPosition, bool hidden, int avatarXPosition, int avatarYPosition, string hero)"

.PP
\fBParameters\fP
.RS 4
\fIid\fP 
.br
\fIname\fP The name of the character that will be visible on Shard shop, character selection, etc
.br
\fIspriteName\fP The name of the sprite file that will loaded on the home button and on the profile card
.br
\fIspriteBackgroundName\fP The sprite background that will be shown on the profile card, behind the avatar
.br
\fIcards\fP The cards that can unlock this avatar for the user
.br
\fIstory\fP Which story this avatar is related to
.br
\fIshards\fP How many shards are needed to purchase this character in the shard shop
.br
\fIcompanionInitialYPosition\fP The initialPosition of the character when playing companion\&. Some character might initiate the animation from the bottom, others from the top
.br
\fIhero\fP Inidicates if this character has hero powers
.br
\fIhidden\fP Used to hide the avatar from any selection
.br
\fIavatarXPosition\fP The X position of the avatar inside the home button
.br
\fIavatarYPosition\fP The Y position of the avatar inside the home button
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
