.TH "Achroma.AchromaStoryProgress" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.AchromaStoryProgress
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAchromaStoryProgress\fP (string story, int character, int relic, string lastUpdate, List< string > progress)"
.br
.ti -1c
.RI "Dictionary< string, object > \fBGetDictionary\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBstory\fP"
.br
.ti -1c
.RI "int \fBcharacter\fP"
.br
.ti -1c
.RI "int \fBrelic\fP"
.br
.ti -1c
.RI "string \fBlastUpdate\fP"
.br
.ti -1c
.RI "List< string > \fBprogress\fP = new List<string>()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
