.TH "Achroma.AchromaRemoteConfigDependency" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.AchromaRemoteConfigDependency
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RemoteConfigVariableType \fBremoteConfigType\fP"
.br
.ti -1c
.RI "bool \fBinvertRemoteConfig\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
