.TH "Achroma.AchromaPurchaseOption" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Achroma.AchromaPurchaseOption
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAchromaPurchaseOption\fP (string id, string title, string description, int shards, string iOSProductId, string AndroidProductId)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBId\fP"
.br
.ti -1c
.RI "string \fBTitle\fP"
.br
.ti -1c
.RI "string \fBDescription\fP"
.br
.ti -1c
.RI "int \fBShards\fP"
.br
.ti -1c
.RI "string \fBiOSProductId\fP"
.br
.ti -1c
.RI "string \fBAndroidProductId\fP"
.br
.ti -1c
.RI "string \fBPrice\fP"
.br
.ti -1c
.RI "string \fBCurrency\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCurrencySymbol\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
