.TH "CFX_AutoRotate" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFX_AutoRotate
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3 \fBrotation\fP"
.br
.ti -1c
.RI "Space \fBspace\fP = Space\&.Self"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
