.TH "CFX_Demo_New" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFX_Demo_New
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnToggleGround\fP ()"
.br
.ti -1c
.RI "void \fBOnToggleCamera\fP ()"
.br
.ti -1c
.RI "void \fBOnToggleSlowMo\fP ()"
.br
.ti -1c
.RI "void \fBOnPreviousEffect\fP ()"
.br
.ti -1c
.RI "void \fBOnNextEffect\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Renderer \fBgroundRenderer\fP"
.br
.ti -1c
.RI "Collider \fBgroundCollider\fP"
.br
.ti -1c
.RI "Image \fBslowMoBtn\fP"
.br
.ti -1c
.RI "Text \fBslowMoLabel\fP"
.br
.ti -1c
.RI "Image \fBcamRotBtn\fP"
.br
.ti -1c
.RI "Text \fBcamRotLabel\fP"
.br
.ti -1c
.RI "Image \fBgroundBtn\fP"
.br
.ti -1c
.RI "Text \fBgroundLabel\fP"
.br
.ti -1c
.RI "Text \fBEffectLabel\fP"
.br
.ti -1c
.RI "Text \fBEffectIndexLabel\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
