.TH "CFX_LightFlicker" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFX_LightFlicker
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBloop\fP"
.br
.ti -1c
.RI "float \fBsmoothFactor\fP = 1f"
.br
.ti -1c
.RI "float \fBaddIntensity\fP = 1\&.0f"
.br
.RI "Max intensity will be: baseIntensity + addIntensity\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
