.TH "CFX_Demo_RandomDir" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFX_Demo_RandomDir
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3 \fBmin\fP = new Vector3(0,0,0)"
.br
.ti -1c
.RI "Vector3 \fBmax\fP = new Vector3(0,360,0)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
