.TH "CharacterSelectorAvatarList" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CharacterSelectorAvatarList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAchromaPopupWindow\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLoadAvatars\fP (bool hero, UnityAction callback)"
.br
.RI "Loads the list of chapters on the header of the avatar selection\&. "
.in -1c

Public Member Functions inherited from \fBAchromaPopupWindow\fP
.in +1c
.ti -1c
.RI "void \fBHide\fP ()"
.br
.RI "This will set the element position to the bottom, making it disappear from the screen\&. "
.ti -1c
.RI "virtual void \fBFadeIn\fP (UnityAction result=null)"
.br
.RI "The method that will move the UI element up\&. "
.ti -1c
.RI "virtual void \fBFadeOut\fP (UnityAction result=null)"
.br
.RI "The Coroutine that will move the UI element down\&. "
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBAchromaPopupWindow\fP
.in +1c
.ti -1c
.RI "float \fBspeed\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
