.TH "CharacterSelectorDialogBox" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CharacterSelectorDialogBox
.SH SYNOPSIS
.br
.PP
.PP
Inherits DevionGames\&.UIWidgets\&.DialogBox\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBClose\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
