.TH "CharacterSelector" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CharacterSelector \- Window that allows user to pick a character to play Hero mode or other custom reasons\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLoadAvatars\fP (UnityAction callback)"
.br
.RI "Loads the list of chapters on the header of the avatar selection\&. "
.in -1c
.SH "Detailed Description"
.PP 
Window that allows user to pick a character to play Hero mode or other custom reasons\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
