.TH "CharacterSelectorAvatar" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CharacterSelectorAvatar \- The avatar thumbnail that appears in the character selector screen\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetAvatarType\fP (int value, UnityAction callback)"
.br
.ti -1c
.RI "void \fBUpdateAvatar\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fB_avatarType\fP"
.br
.ti -1c
.RI "Sprite \fBsprite\fP"
.br
.ti -1c
.RI "bool \fBactive\fP"
.br
.ti -1c
.RI "bool \fBmaskable\fP"
.br
.ti -1c
.RI "Material \fBmaterialPrefab\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBavatarName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBavatarType\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBHero\fP\fC [set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The avatar thumbnail that appears in the character selector screen\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
