.TH "ChatController" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChatController
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TMP_InputField \fBChatInputField\fP"
.br
.ti -1c
.RI "TMP_Text \fBChatDisplayOutput\fP"
.br
.ti -1c
.RI "Scrollbar \fBChatScrollbar\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
