.TH "Components.ImageHolder" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Components.ImageHolder
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Image \fBBackgroundImage\fP"
.br
.ti -1c
.RI "Button \fBForegroundButton\fP"
.br
.ti -1c
.RI "Image \fBBrokenImageIcon\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
