.TH "Components.ViewCartButton" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Components.ViewCartButton
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdateCartQuantity\fP (int quantity)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBQuantity\fP"
.br
.ti -1c
.RI "Image \fBSingleDigitBadge\fP"
.br
.ti -1c
.RI "Image \fBDoubleDigitBadge\fP"
.br
.ti -1c
.RI "Image \fBCartIcon\fP"
.br
.ti -1c
.RI "UnityEvent \fBOnClick\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
