.TH "ContextMenuTrigger" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContextMenuTrigger
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, and IPointerDownHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPointerDown\fP (PointerEventData eventData)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string[] \fBmenu\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
