.TH "deprecated" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 
.PP

.IP "\fBMember \fBShopify\&.Unity\&.AppliedGiftCard\&.amountUsed\fP ()\fP" 1c
Use \fCamountUsedV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.AppliedGiftCard\&.balance\fP ()\fP" 1c
Use \fCbalanceV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Article\&.author\fP ()\fP" 1c
Use \fCauthorV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Checkout\&.customer\fP ()\fP" 1c
This field will always return null\&. If you have an authentication token for the customer, you can use the \fCcustomer\fP field on the query root to retrieve it\&.  
.IP "\fBMember \fBShopify\&.Unity\&.Checkout\&.paymentDue\fP ()\fP" 1c
Use \fCpaymentDueV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Checkout\&.subtotalPrice\fP ()\fP" 1c
Use \fCsubtotalPriceV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Checkout\&.totalPrice\fP ()\fP" 1c
Use \fCtotalPriceV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Checkout\&.totalTax\fP ()\fP" 1c
Use \fCtotalTaxV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutAttributesUpdatePayload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutAttributesUpdateV2payload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutCompleteFreePayload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutCompleteWithCreditCardPayload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutCompleteWithCreditCardV2payload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutCompleteWithTokenizedPaymentPayload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutCompleteWithTokenizedPaymentV2payload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutCreatePayload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutCustomerAssociateV2payload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutCustomerDisassociatePayload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutCustomerDisassociateV2payload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutDiscountCodeApplyPayload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutDiscountCodeApplyV2payload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutDiscountCodeRemovePayload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutEmailUpdatePayload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutEmailUpdateV2payload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutGiftCardApplyPayload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutGiftCardRemovePayload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutGiftCardRemoveV2payload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutGiftCardsAppendPayload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutLineItemsAddPayload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutLineItemsRemovePayload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutLineItemsUpdatePayload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutShippingAddressUpdatePayload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutShippingAddressUpdateV2payload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CheckoutShippingLineUpdatePayload\&.userErrors\fP ()\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CustomerAccessTokenCreatePayload\&.userErrors\fP ()\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CustomerActivatePayload\&.userErrors\fP ()\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CustomerAddressCreatePayload\&.userErrors\fP ()\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CustomerAddressDeletePayload\&.userErrors\fP ()\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CustomerAddressUpdatePayload\&.userErrors\fP ()\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CustomerCreatePayload\&.userErrors\fP ()\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CustomerDefaultAddressUpdatePayload\&.userErrors\fP ()\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CustomerRecoverPayload\&.userErrors\fP ()\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CustomerResetByUrlPayload\&.userErrors\fP ()\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CustomerResetPayload\&.userErrors\fP ()\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.CustomerUpdatePayload\&.userErrors\fP ()\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.AppliedGiftCardQuery\&.amountUsed\fP ()\fP" 1c
Use \fCamountUsedV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.AppliedGiftCardQuery\&.balance\fP ()\fP" 1c
Use \fCbalanceV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.ArticleQuery\&.author\fP (ArticleAuthorDelegate buildQuery)\fP" 1c
Use \fCauthorV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutAttributesUpdatePayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutAttributesUpdateV2payloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutCompleteFreePayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutCompleteWithCreditCardPayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutCompleteWithCreditCardV2payloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutCompleteWithTokenizedPaymentPayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutCompleteWithTokenizedPaymentV2payloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutCreatePayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutCustomerAssociateV2payloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutCustomerDisassociatePayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutCustomerDisassociateV2payloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutDiscountCodeApplyPayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutDiscountCodeApplyV2payloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutDiscountCodeRemovePayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutEmailUpdatePayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutEmailUpdateV2payloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutGiftCardApplyPayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutGiftCardRemovePayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutGiftCardRemoveV2payloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutGiftCardsAppendPayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutLineItemsAddPayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutLineItemsRemovePayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutLineItemsUpdatePayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutQuery\&.customer\fP (CustomerDelegate buildQuery)\fP" 1c
This field will always return null\&. If you have an authentication token for the customer, you can use the \fCcustomer\fP field on the query root to retrieve it\&.  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutQuery\&.paymentDue\fP ()\fP" 1c
Use \fCpaymentDueV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutQuery\&.subtotalPrice\fP ()\fP" 1c
Use \fCsubtotalPriceV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutQuery\&.totalPrice\fP ()\fP" 1c
Use \fCtotalPriceV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutQuery\&.totalTax\fP ()\fP" 1c
Use \fCtotalTaxV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutShippingAddressUpdatePayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutShippingAddressUpdateV2payloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CheckoutShippingLineUpdatePayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcheckoutUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CustomerAccessTokenCreatePayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CustomerActivatePayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CustomerAddressCreatePayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CustomerAddressDeletePayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CustomerAddressUpdatePayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CustomerCreatePayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CustomerDefaultAddressUpdatePayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CustomerRecoverPayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CustomerResetByUrlPayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CustomerResetPayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.CustomerUpdatePayloadQuery\&.userErrors\fP (UserErrorDelegate buildQuery)\fP" 1c
Use \fCcustomerUserErrors\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.ImageQuery\&.src\fP ()\fP" 1c
Previously an image had a single \fCsrc\fP field\&. This could either return the original image location or a URL that contained transformations such as sizing or scale\&. 
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.MailingAddressQuery\&.countryCode\fP ()\fP" 1c
Use \fCcountryCodeV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.MutationQuery\&.checkoutAttributesUpdate\fP (CheckoutAttributesUpdatePayloadDelegate buildQuery, string checkoutId, \fBCheckoutAttributesUpdateInput\fP input, string alias=null)\fP" 1c
Use \fCcheckoutAttributesUpdateV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.MutationQuery\&.checkoutCompleteWithCreditCard\fP (CheckoutCompleteWithCreditCardPayloadDelegate buildQuery, string checkoutId, \fBCreditCardPaymentInput\fP payment, string alias=null)\fP" 1c
Use \fCcheckoutCompleteWithCreditCardV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.MutationQuery\&.checkoutCompleteWithTokenizedPayment\fP (CheckoutCompleteWithTokenizedPaymentPayloadDelegate buildQuery, string checkoutId, \fBTokenizedPaymentInput\fP payment, string alias=null)\fP" 1c
Use \fCcheckoutCompleteWithTokenizedPaymentV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.MutationQuery\&.checkoutCompleteWithTokenizedPaymentV2\fP (CheckoutCompleteWithTokenizedPaymentV2payloadDelegate buildQuery, string checkoutId, \fBTokenizedPaymentInputV2\fP payment, string alias=null)\fP" 1c
Use \fCcheckoutCompleteWithTokenizedPaymentV3\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.MutationQuery\&.checkoutCustomerAssociate\fP (CheckoutCustomerAssociatePayloadDelegate buildQuery, string checkoutId, string customerAccessToken, string alias=null)\fP" 1c
Use \fCcheckoutCustomerAssociateV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.MutationQuery\&.checkoutCustomerDisassociate\fP (CheckoutCustomerDisassociatePayloadDelegate buildQuery, string checkoutId, string alias=null)\fP" 1c
Use \fCcheckoutCustomerDisassociateV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.MutationQuery\&.checkoutDiscountCodeApply\fP (CheckoutDiscountCodeApplyPayloadDelegate buildQuery, string discountCode, string checkoutId, string alias=null)\fP" 1c
Use \fCcheckoutDiscountCodeApplyV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.MutationQuery\&.checkoutEmailUpdate\fP (CheckoutEmailUpdatePayloadDelegate buildQuery, string checkoutId, string email, string alias=null)\fP" 1c
Use \fCcheckoutEmailUpdateV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.MutationQuery\&.checkoutGiftCardApply\fP (CheckoutGiftCardApplyPayloadDelegate buildQuery, string giftCardCode, string checkoutId, string alias=null)\fP" 1c
Use \fCcheckoutGiftCardsAppend\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.MutationQuery\&.checkoutGiftCardRemove\fP (CheckoutGiftCardRemovePayloadDelegate buildQuery, string appliedGiftCardId, string checkoutId, string alias=null)\fP" 1c
Use \fCcheckoutGiftCardRemoveV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.MutationQuery\&.checkoutShippingAddressUpdate\fP (CheckoutShippingAddressUpdatePayloadDelegate buildQuery, \fBMailingAddressInput\fP shippingAddress, string checkoutId, string alias=null)\fP" 1c
Use \fCcheckoutShippingAddressUpdateV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.OrderQuery\&.subtotalPrice\fP ()\fP" 1c
Use \fCsubtotalPriceV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.OrderQuery\&.totalPrice\fP ()\fP" 1c
Use \fCtotalPriceV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.OrderQuery\&.totalRefunded\fP ()\fP" 1c
Use \fCtotalRefundedV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.OrderQuery\&.totalShippingPrice\fP ()\fP" 1c
Use \fCtotalShippingPriceV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.OrderQuery\&.totalTax\fP ()\fP" 1c
Use \fCtotalTaxV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.PaymentQuery\&.amount\fP ()\fP" 1c
Use \fCamountV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.ProductVariantQuery\&.available\fP ()\fP" 1c
Use \fCavailableForSale\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.ProductVariantQuery\&.compareAtPrice\fP ()\fP" 1c
Use \fCcompareAtPriceV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.ProductVariantQuery\&.price\fP ()\fP" 1c
Use \fCpriceV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.ScriptDiscountApplicationQuery\&.description\fP ()\fP" 1c
Use \fCtitle\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.ShippingRateQuery\&.price\fP ()\fP" 1c
Use \fCpriceV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.ShopQuery\&.articles\fP (ArticleConnectionDelegate buildQuery, long? first=null, string after=null, long? last=null, string before=null, bool? reverse=null, ArticleSortKeys? sortKey=null, string queryValue=null, string alias=null)\fP" 1c
Use \fC\fBQueryRoot\&.articles\fP\fP instead\&.  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.ShopQuery\&.blogs\fP (BlogConnectionDelegate buildQuery, long? first=null, string after=null, long? last=null, string before=null, bool? reverse=null, BlogSortKeys? sortKey=null, string queryValue=null, string alias=null)\fP" 1c
Use \fC\fBQueryRoot\&.blogs\fP\fP instead\&.  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.ShopQuery\&.collectionByHandle\fP (CollectionDelegate buildQuery, string handle, string alias=null)\fP" 1c
Use \fC\fBQueryRoot\&.collectionByHandle\fP\fP instead\&.  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.ShopQuery\&.collections\fP (CollectionConnectionDelegate buildQuery, long? first=null, string after=null, long? last=null, string before=null, bool? reverse=null, CollectionSortKeys? sortKey=null, string queryValue=null, string alias=null)\fP" 1c
Use \fC\fBQueryRoot\&.collections\fP\fP instead\&.  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.ShopQuery\&.currencyCode\fP ()\fP" 1c
Use \fCpaymentSettings\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.ShopQuery\&.productByHandle\fP (ProductDelegate buildQuery, string handle, string alias=null)\fP" 1c
Use \fC\fBQueryRoot\&.productByHandle\fP\fP instead\&.  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.ShopQuery\&.products\fP (ProductConnectionDelegate buildQuery, long? first=null, string after=null, long? last=null, string before=null, bool? reverse=null, ProductSortKeys? sortKey=null, string queryValue=null, string alias=null)\fP" 1c
Use \fC\fBQueryRoot\&.products\fP\fP instead\&.  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.ShopQuery\&.productTags\fP (StringConnectionDelegate buildQuery, long first, string alias=null)\fP" 1c
Use \fC\fBQueryRoot\&.productTags\fP\fP instead\&.  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.ShopQuery\&.productTypes\fP (StringConnectionDelegate buildQuery, long first, string alias=null)\fP" 1c
Use \fC\fBQueryRoot\&.productTypes\fP\fP instead\&.  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.ShopQuery\&.shopifyPaymentsAccountId\fP ()\fP" 1c
Use \fCpaymentSettings\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.TransactionQuery\&.amount\fP ()\fP" 1c
Use \fCamountV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.GraphQL\&.TransactionQuery\&.status\fP ()\fP" 1c
Use \fCstatusV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Image\&.src\fP ()\fP" 1c
Previously an image had a single \fCsrc\fP field\&. This could either return the original image location or a URL that contained transformations such as sizing or scale\&. 
.IP "\fBMember \fBShopify\&.Unity\&.MailingAddress\&.countryCode\fP ()\fP" 1c
Use \fCcountryCodeV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Mutation\&.checkoutAttributesUpdate\fP (string alias=null)\fP" 1c
Use \fCcheckoutAttributesUpdateV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Mutation\&.checkoutCompleteWithCreditCard\fP (string alias=null)\fP" 1c
Use \fCcheckoutCompleteWithCreditCardV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Mutation\&.checkoutCompleteWithTokenizedPayment\fP (string alias=null)\fP" 1c
Use \fCcheckoutCompleteWithTokenizedPaymentV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Mutation\&.checkoutCompleteWithTokenizedPaymentV2\fP (string alias=null)\fP" 1c
Use \fCcheckoutCompleteWithTokenizedPaymentV3\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Mutation\&.checkoutCustomerAssociate\fP (string alias=null)\fP" 1c
Use \fCcheckoutCustomerAssociateV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Mutation\&.checkoutCustomerDisassociate\fP (string alias=null)\fP" 1c
Use \fCcheckoutCustomerDisassociateV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Mutation\&.checkoutDiscountCodeApply\fP (string alias=null)\fP" 1c
Use \fCcheckoutDiscountCodeApplyV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Mutation\&.checkoutEmailUpdate\fP (string alias=null)\fP" 1c
Use \fCcheckoutEmailUpdateV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Mutation\&.checkoutGiftCardApply\fP (string alias=null)\fP" 1c
Use \fCcheckoutGiftCardsAppend\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Mutation\&.checkoutGiftCardRemove\fP (string alias=null)\fP" 1c
Use \fCcheckoutGiftCardRemoveV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Mutation\&.checkoutShippingAddressUpdate\fP (string alias=null)\fP" 1c
Use \fCcheckoutShippingAddressUpdateV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Order\&.subtotalPrice\fP ()\fP" 1c
Use \fCsubtotalPriceV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Order\&.totalPrice\fP ()\fP" 1c
Use \fCtotalPriceV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Order\&.totalRefunded\fP ()\fP" 1c
Use \fCtotalRefundedV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Order\&.totalShippingPrice\fP ()\fP" 1c
Use \fCtotalShippingPriceV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Order\&.totalTax\fP ()\fP" 1c
Use \fCtotalTaxV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Payment\&.amount\fP ()\fP" 1c
Use \fCamountV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.ProductVariant\&.available\fP ()\fP" 1c
Use \fCavailableForSale\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.ProductVariant\&.compareAtPrice\fP ()\fP" 1c
Use \fCcompareAtPriceV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.ProductVariant\&.price\fP ()\fP" 1c
Use \fCpriceV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.ScriptDiscountApplication\&.description\fP ()\fP" 1c
Use \fCtitle\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.ShippingRate\&.price\fP ()\fP" 1c
Use \fCpriceV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Shop\&.articles\fP (string alias=null)\fP" 1c
Use \fC\fBQueryRoot\&.articles\fP\fP instead\&.  
.IP "\fBMember \fBShopify\&.Unity\&.Shop\&.blogs\fP (string alias=null)\fP" 1c
Use \fC\fBQueryRoot\&.blogs\fP\fP instead\&.  
.IP "\fBMember \fBShopify\&.Unity\&.Shop\&.collectionByHandle\fP (string alias=null)\fP" 1c
Use \fC\fBQueryRoot\&.collectionByHandle\fP\fP instead\&.  
.IP "\fBMember \fBShopify\&.Unity\&.Shop\&.collections\fP (string alias=null)\fP" 1c
Use \fC\fBQueryRoot\&.collections\fP\fP instead\&.  
.IP "\fBMember \fBShopify\&.Unity\&.Shop\&.currencyCode\fP ()\fP" 1c
Use \fCpaymentSettings\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Shop\&.productByHandle\fP (string alias=null)\fP" 1c
Use \fC\fBQueryRoot\&.productByHandle\fP\fP instead\&.  
.IP "\fBMember \fBShopify\&.Unity\&.Shop\&.products\fP (string alias=null)\fP" 1c
Use \fC\fBQueryRoot\&.products\fP\fP instead\&.  
.IP "\fBMember \fBShopify\&.Unity\&.Shop\&.productTags\fP (string alias=null)\fP" 1c
Use \fC\fBQueryRoot\&.productTags\fP\fP instead\&.  
.IP "\fBMember \fBShopify\&.Unity\&.Shop\&.productTypes\fP (string alias=null)\fP" 1c
Use \fC\fBQueryRoot\&.productTypes\fP\fP instead\&.  
.IP "\fBMember \fBShopify\&.Unity\&.Shop\&.shopifyPaymentsAccountId\fP ()\fP" 1c
Use \fCpaymentSettings\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Transaction\&.amount\fP ()\fP" 1c
Use \fCamountV2\fP instead  
.IP "\fBMember \fBShopify\&.Unity\&.Transaction\&.status\fP ()\fP" 1c
Use \fCstatusV2\fP instead 
.PP

