.TH "DevionGames.UIWidgets.IValidation< T >" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.UIWidgets.IValidation< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBValidate\fP (T item)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
