.TH "DevionGames.EventHandler" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.EventHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBExecute\fP (string eventName)"
.br
.ti -1c
.RI "static void \fBExecute\fP (object obj, string eventName)"
.br
.ti -1c
.RI "static void \fBExecute< T1 >\fP (string eventName, T1 arg1)"
.br
.ti -1c
.RI "static void \fBExecute< T1 >\fP (object obj, string eventName, T1 arg1)"
.br
.ti -1c
.RI "static void \fBExecute< T1, T2 >\fP (string eventName, T1 arg1, T2 arg2)"
.br
.ti -1c
.RI "static void \fBExecute< T1, T2 >\fP (object obj, string eventName, T1 arg1, T2 arg2)"
.br
.ti -1c
.RI "static void \fBExecute< T1, T2, T3 >\fP (string eventName, T1 arg1, T2 arg2, T3 arg3)"
.br
.ti -1c
.RI "static void \fBExecute< T1, T2, T3 >\fP (object obj, string eventName, T1 arg1, T2 arg2, T3 arg3)"
.br
.ti -1c
.RI "static void \fBRegister\fP (string eventName, System\&.Action handler)"
.br
.ti -1c
.RI "static void \fBRegister\fP (object obj, string eventName, System\&.Action handler)"
.br
.ti -1c
.RI "static void \fBRegister< T1 >\fP (string eventName, Action< T1 > handler)"
.br
.ti -1c
.RI "static void \fBRegister< T1 >\fP (object obj, string eventName, Action< T1 > handler)"
.br
.ti -1c
.RI "static void \fBRegister< T1, T2 >\fP (string eventName, Action< T1, T2 > handler)"
.br
.ti -1c
.RI "static void \fBRegister< T1, T2 >\fP (object obj, string eventName, Action< T1, T2 > handler)"
.br
.ti -1c
.RI "static void \fBRegister< T1, T2, T3 >\fP (string eventName, Action< T1, T2, T3 > handler)"
.br
.ti -1c
.RI "static void \fBRegister< T1, T2, T3 >\fP (object obj, string eventName, Action< T1, T2, T3 > handler)"
.br
.ti -1c
.RI "static void \fBUnregister\fP (string eventName, System\&.Action handler)"
.br
.ti -1c
.RI "static void \fBUnregister\fP (object obj, string eventName, System\&.Action handler)"
.br
.ti -1c
.RI "static void \fBUnregister< T1 >\fP (string eventName, Action< T1 > handler)"
.br
.ti -1c
.RI "static void \fBUnregister< T1 >\fP (object obj, string eventName, Action< T1 > handler)"
.br
.ti -1c
.RI "static void \fBUnregister< T1, T2 >\fP (string eventName, Action< T1, T2 > handler)"
.br
.ti -1c
.RI "static void \fBUnregister< T1, T2 >\fP (object obj, string eventName, Action< T1, T2 > handler)"
.br
.ti -1c
.RI "static void \fBUnregister< T1, T2, T3 >\fP (string eventName, Action< T1, T2, T3 > handler)"
.br
.ti -1c
.RI "static void \fBUnregister< T1, T2, T3 >\fP (object obj, string eventName, Action< T1, T2, T3 > handler)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
