.TH "DevionGames.StringVariable" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.StringVariable
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDevionGames\&.Variable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStringVariable\fP (string name)"
.br
.in -1c

Public Member Functions inherited from \fBDevionGames\&.Variable\fP
.in +1c
.ti -1c
.RI "\fBVariable\fP (string name)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static implicit \fBoperator StringVariable\fP (string value)"
.br
.ti -1c
.RI "static implicit \fBoperator string\fP (\fBStringVariable\fP value)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBValue\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "override object \fBRawValue\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "override System\&.Type \fBtype\fP\fC [get]\fP"
.br
.in -1c

Properties inherited from \fBDevionGames\&.Variable\fP
.in +1c
.ti -1c
.RI "virtual string \fBname\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual bool \fBisShared\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual bool \fBisNone\fP\fC [get]\fP"
.br
.ti -1c
.RI "Type \fBtype\fP\fC [get]\fP"
.br
.ti -1c
.RI "object \fBRawValue\fP\fC [get, set]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
