.TH "DevionGames.Blackboard" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.Blackboard
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "T \fBGetValue< T >\fP (string name)"
.br
.ti -1c
.RI "T \fBGetValue< T >\fP (\fBVariable\fP variable)"
.br
.ti -1c
.RI "void \fBSetValue< T >\fP (string name, object value)"
.br
.ti -1c
.RI "void \fBSetValue\fP (string name, object value, Type type)"
.br
.ti -1c
.RI "bool \fBDeleteVariable\fP (string name)"
.br
.ti -1c
.RI "\fBVariable\fP \fBGetVariable\fP (string name)"
.br
.ti -1c
.RI "void \fBAddVariable\fP (\fBVariable\fP variable)"
.br
.ti -1c
.RI "\fBVariable\fP \fBAddVariable< T >\fP (string name, object value)"
.br
.ti -1c
.RI "\fBVariable\fP \fBAddVariable\fP (string name, object value, Type type)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "List< \fBVariable\fP > \fBm_Variables\fP = new List<\fBVariable\fP>()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
