.TH "DevionGames.Variable" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.Variable
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDevionGames\&.ArrayListVariable\fP, \fBDevionGames\&.BoolVariable\fP, \fBDevionGames\&.ColorVariable\fP, \fBDevionGames\&.FloatVariable\fP, \fBDevionGames\&.GameObjectVariable\fP, \fBDevionGames\&.IntVariable\fP, \fBDevionGames\&.ObjectVariable\fP, \fBDevionGames\&.StringVariable\fP, \fBDevionGames\&.Vector2Variable\fP, and \fBDevionGames\&.Vector3Variable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVariable\fP (string name)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual string \fBname\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual bool \fBisShared\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual bool \fBisNone\fP\fC [get]\fP"
.br
.ti -1c
.RI "Type \fBtype\fP\fC [get]\fP"
.br
.ti -1c
.RI "object \fBRawValue\fP\fC [get, set]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
