.TH "DevionGames.UIWidgets.Tab" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.UIWidgets.Tab
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTabEvent\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSelect\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TabElementToChangeColor \fBelementToChangeColor\fP"
.br
.ti -1c
.RI "Color \fBselectedColor\fP"
.br
.ti -1c
.RI "bool \fBisOn\fP"
.br
.ti -1c
.RI "\fBTabEvent\fP \fBonSelect\fP =new \fBTabEvent\fP()"
.br
.ti -1c
.RI "\fBTabEvent\fP \fBonDeselect\fP = new \fBTabEvent\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
