.TH "DevionGames.UIWidgets.Spinner" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.UIWidgets.Spinner
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSpinnerEvent\fP"
.br
.ti -1c
.RI "class \fBSpinnerTextEvent\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetCurrent\fP (string value)"
.br
.ti -1c
.RI "void \fBStartIncrease\fP ()"
.br
.ti -1c
.RI "void \fBStartDecrease\fP ()"
.br
.ti -1c
.RI "void \fBStop\fP ()"
.br
.ti -1c
.RI "IEnumerator \fBIncrease\fP ()"
.br
.ti -1c
.RI "IEnumerator \fBDecrease\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBchangeDelay\fP = 0\&.1f"
.br
.ti -1c
.RI "float \fBstep\fP = 1\&.0f"
.br
.ti -1c
.RI "float \fBmin\fP"
.br
.ti -1c
.RI "float \fBmax\fP"
.br
.ti -1c
.RI "\fBSpinnerEvent\fP \fBonChange\fP =new \fBSpinnerEvent\fP()"
.br
.ti -1c
.RI "\fBSpinnerTextEvent\fP \fBm_OnChange\fP =new \fBSpinnerTextEvent\fP()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBcurrent\fP\fC [get, set]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
