.TH "DevionGames.UIWidgets.ResizePanel" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.UIWidgets.ResizePanel
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, IPointerDownHandler, and IDragHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPointerDown\fP (PointerEventData data)"
.br
.ti -1c
.RI "void \fBOnDrag\fP (PointerEventData data)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector2 \fBminSize\fP = new Vector2 (100, 100)"
.br
.ti -1c
.RI "Vector2 \fBmaxSize\fP = new Vector2 (400, 400)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
