.TH "DevionGames.UIWidgets.NotificationSlot" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.UIWidgets.NotificationSlot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDevionGames\&.UIWidgets\&.UISlot< NotificationOptions >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBRepaint\fP ()"
.br
.RI "Repaint slot visuals with item information\&. "
.in -1c

Public Member Functions inherited from \fBDevionGames\&.UIWidgets\&.UISlot< NotificationOptions >\fP
.in +1c
.ti -1c
.RI "virtual bool \fBCanAddItem\fP (T item)"
.br
.RI "Can the item be added to this slot\&. This does not check if the slot is empty\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "TMPro\&.TMP_Text \fBm_Text\fP"
.br
.RI "Notification text to display\&. "
.ti -1c
.RI "Image \fBm_Background\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Properties inherited from \fBDevionGames\&.UIWidgets\&.UISlot< NotificationOptions >\fP
.in +1c
.ti -1c
.RI "\fBUIContainer\fP< T > \fBContainer\fP\fC [get, set]\fP"
.br
.RI "The item container that holds this slot\&. "
.ti -1c
.RI "int \fBIndex\fP\fC [get, set]\fP"
.br
.RI "Index of item container\&. "
.ti -1c
.RI "virtual T \fBObservedItem\fP\fC [get, set]\fP"
.br
.RI "The item this slot is holding\&. "
.ti -1c
.RI "bool \fBIsEmpty\fP\fC [get]\fP"
.br
.RI "Checks if the slot is empty ObservedItem == null\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void DevionGames\&.UIWidgets\&.NotificationSlot\&.Repaint ()\fC [virtual]\fP"

.PP
Repaint slot visuals with item information\&. 
.PP
Reimplemented from \fBDevionGames\&.UIWidgets\&.UISlot< NotificationOptions >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
