.TH "DevionGames.PropertyBinding.PropertyRef" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.PropertyBinding.PropertyRef
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBGetValue\fP ()"
.br
.ti -1c
.RI "bool \fBSetValue\fP (object value)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Component \fBcomponent\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBpropertyPath\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
