.TH "DevionGames.UtilityBehavior" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.UtilityBehavior
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBQuitApplication\fP ()"
.br
.ti -1c
.RI "void \fBLoadScene\fP (string scene)"
.br
.ti -1c
.RI "void \fBInstantiate\fP (GameObject gameObject)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
