.TH "DevionGames" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnimationEventSender\fP"
.br
.ti -1c
.RI "class \fBArgumentVariable\fP"
.br
.ti -1c
.RI "class \fBArrayListVariable\fP"
.br
.ti -1c
.RI "class \fBAudioEventListener\fP"
.br
.ti -1c
.RI "class \fBAudioPlaylist\fP"
.br
.ti -1c
.RI "class \fBBlackboard\fP"
.br
.ti -1c
.RI "class \fBBoolVariable\fP"
.br
.ti -1c
.RI "class \fBCallbackEventData\fP"
.br
.RI "Callback event data that can be derived from\&. "
.ti -1c
.RI "class \fBCallbackHandler\fP"
.br
.RI "Callback handler for custom events\&. "
.ti -1c
.RI "class \fBCameraEffects\fP"
.br
.RI "Camera Effects\&. "
.ti -1c
.RI "class \fBCategoryAttribute\fP"
.br
.ti -1c
.RI "class \fBColorVariable\fP"
.br
.ti -1c
.RI "class \fBComponentMenu\fP"
.br
.ti -1c
.RI "class \fBCompoundAttribute\fP"
.br
.ti -1c
.RI "class \fBCoroutineHandler\fP"
.br
.ti -1c
.RI "class \fBCoroutineQueue\fP"
.br
.ti -1c
.RI "class \fBDontDestroyOnLoad\fP"
.br
.ti -1c
.RI "class \fBEnumFlagsAttribute\fP"
.br
.ti -1c
.RI "class \fBEventHandler\fP"
.br
.ti -1c
.RI "class \fBExcludeFromCreation\fP"
.br
.ti -1c
.RI "class \fBFloatVariable\fP"
.br
.ti -1c
.RI "class \fBGameObjectVariable\fP"
.br
.ti -1c
.RI "class \fBHeaderLineAttribute\fP"
.br
.ti -1c
.RI "class \fBIconAttribute\fP"
.br
.ti -1c
.RI "interface \fBIIdentity\fP"
.br
.ti -1c
.RI "interface \fBIJsonSerializable\fP"
.br
.ti -1c
.RI "interface \fBINameable\fP"
.br
.ti -1c
.RI "class \fBInspectorLabelAttribute\fP"
.br
.ti -1c
.RI "class \fBIntVariable\fP"
.br
.ti -1c
.RI "interface \fBISelectable\fP"
.br
.ti -1c
.RI "class \fBJsonSerializer\fP"
.br
.ti -1c
.RI "class \fBLookAtMainCamera\fP"
.br
.ti -1c
.RI "class \fBMiniJSON\fP"
.br
.ti -1c
.RI "class \fBMinMaxSliderAttribute\fP"
.br
.ti -1c
.RI "class \fBMoveForward\fP"
.br
.ti -1c
.RI "class \fBMoveTo\fP"
.br
.ti -1c
.RI "class \fBNamedVariable\fP"
.br
.ti -1c
.RI "class \fBObjectProperty\fP"
.br
.ti -1c
.RI "class \fBObjectVariable\fP"
.br
.ti -1c
.RI "class \fBPlayAudioClip\fP"
.br
.ti -1c
.RI "class \fBPlayerInfo\fP"
.br
.ti -1c
.RI "class \fBPropertyBinding\fP"
.br
.ti -1c
.RI "class \fBSaveUIComponent\fP"
.br
.ti -1c
.RI "class \fBSelectableObject\fP"
.br
.ti -1c
.RI "class \fBSelectableObjectName\fP"
.br
.ti -1c
.RI "class \fBSelectionHandler\fP"
.br
.ti -1c
.RI "class \fBSetCursorLockState\fP"
.br
.ti -1c
.RI "class \fBSettings\fP"
.br
.ti -1c
.RI "class \fBSharedAttribute\fP"
.br
.ti -1c
.RI "class \fBSimpleMinimap\fP"
.br
.ti -1c
.RI "class \fBSingleInstance\fP"
.br
.ti -1c
.RI "class \fBStringVariable\fP"
.br
.ti -1c
.RI "class \fBTimedDestroy\fP"
.br
.ti -1c
.RI "class \fBTimedEnable\fP"
.br
.ti -1c
.RI "class \fBUnityTools\fP"
.br
.ti -1c
.RI "class \fBUtility\fP"
.br
.ti -1c
.RI "class \fBUtilityBehavior\fP"
.br
.ti -1c
.RI "class \fBVariable\fP"
.br
.ti -1c
.RI "class \fBVector2Variable\fP"
.br
.ti -1c
.RI "class \fBVector3Variable\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBArgumentType\fP { \fBNone\fP, \fBBool\fP, \fBInt\fP, \fBFloat\fP, \fBString\fP, \fBVector2\fP, \fBVector3\fP, \fBColor\fP, \fBObject\fP }"
.br
.ti -1c
.RI "enum \fBVariableType\fP { \fBNone\fP, \fBBool\fP, \fBColor\fP, \fBFloat\fP, \fBGameObject\fP, \fBInt\fP, \fBObject\fP, \fBString\fP, \fBVector2\fP, \fBVector3\fP }"
.br
.ti -1c
.RI "enum \fBNamedVariableType\fP : int { \fBString\fP = 0, \fBBool\fP = 2, \fBColor\fP = 3, \fBFloat\fP = 4, \fBObject\fP = 5, \fBInt\fP = 6, \fBVector2\fP = 7, \fBVector3\fP = 8 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
