.TH "DevionGames.UIWidgets.UICursor" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.UIWidgets.UICursor
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetAnimatorState\fP (string animatorState)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBClear\fP ()"
.br
.ti -1c
.RI "static void \fBSet\fP (Sprite sprite)"
.br
.ti -1c
.RI "static void \fBSet\fP (Sprite sprite, Vector2 size, bool showCursor, string animatorState)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
