.TH "DevionGames.PlayerInfo" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.PlayerInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayerInfo\fP (string tag)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "GameObject \fBgameObject\fP\fC [get]\fP"
.br
.ti -1c
.RI "Transform \fBtransform\fP\fC [get]\fP"
.br
.ti -1c
.RI "Collider \fBcollider\fP\fC [get]\fP"
.br
.ti -1c
.RI "Collider2D \fBcollider2D\fP\fC [get]\fP"
.br
.ti -1c
.RI "Animator \fBanimator\fP\fC [get]\fP"
.br
.ti -1c
.RI "Bounds \fBbounds\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
