.TH "DevionGames.ArgumentVariable" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.ArgumentVariable
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBGetValue\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBGetPropertyValuePath\fP (ArgumentType argumentType)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ArgumentType \fBArgumentType\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsNone\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
