.TH "DevionGames.UIWidgets" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.UIWidgets
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChat\fP"
.br
.ti -1c
.RI "class \fBContextMenu\fP"
.br
.ti -1c
.RI "class \fBDialogBox\fP"
.br
.ti -1c
.RI "class \fBDragPanel\fP"
.br
.ti -1c
.RI "class \fBEasingEquations\fP"
.br
.ti -1c
.RI "struct \fBFloatTween\fP"
.br
.ti -1c
.RI "interface \fBITweenValue\fP"
.br
.ti -1c
.RI "interface \fBIValidation\fP"
.br
.ti -1c
.RI "class \fBJoystick\fP"
.br
.ti -1c
.RI "class \fBMenuItem\fP"
.br
.ti -1c
.RI "class \fBNotification\fP"
.br
.ti -1c
.RI "class \fBNotificationOptions\fP"
.br
.RI "Message options\&. "
.ti -1c
.RI "class \fBNotificationSlot\fP"
.br
.ti -1c
.RI "class \fBProgressbar\fP"
.br
.ti -1c
.RI "class \fBRadialMenu\fP"
.br
.ti -1c
.RI "class \fBResizePanel\fP"
.br
.ti -1c
.RI "class \fBSpinner\fP"
.br
.ti -1c
.RI "class \fBStringPairSlot\fP"
.br
.ti -1c
.RI "class \fBTab\fP"
.br
.ti -1c
.RI "class \fBTooltip\fP"
.br
.ti -1c
.RI "class \fBTooltipTrigger\fP"
.br
.RI "Tooltip trigger to display fixed tooltips\&. "
.ti -1c
.RI "class \fBTweenRunner\fP"
.br
.ti -1c
.RI "class \fBUIContainer\fP"
.br
.ti -1c
.RI "class \fBUICursor\fP"
.br
.ti -1c
.RI "class \fBUISlot\fP"
.br
.ti -1c
.RI "class \fBUIWidget\fP"
.br
.ti -1c
.RI "struct \fBVector3Tween\fP"
.br
.ti -1c
.RI "class \fBWidgetInputHandler\fP"
.br
.ti -1c
.RI "class \fBWidgetUtility\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTabElementToChangeColor\fP { \fBBackground\fP, \fBText\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
