.TH "DevionGames.UIWidgets.Joystick" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.UIWidgets.Joystick
.SH SYNOPSIS
.br
.PP
.PP
Inherits Selectable, and IDragHandler\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJoystickEvent\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnDrag\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "override void \fBOnPointerDown\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "override void \fBOnPointerUp\fP (PointerEventData eventData)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBJoystickEvent\fP \fBonChange\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBStart\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Vector2 \fBposition\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
