.TH "DevionGames.Changelog" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.Changelog
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBversion\fP"
.br
.ti -1c
.RI "string[] \fBchanges\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
