.TH "DevionGames.UIWidgets.StringPairSlot" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.UIWidgets.StringPairSlot
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBRepaint\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Text \fBm_Key\fP"
.br
.ti -1c
.RI "Text \fBm_Value\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "KeyValuePair< string, string > \fBTarget\fP\fC [get, set]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
