.TH "DevionGames.ISelectable" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.ISelectable
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDevionGames\&.SelectableObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnSelect\fP ()"
.br
.ti -1c
.RI "void \fBOnDeselect\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBenabled\fP\fC [get]\fP"
.br
.ti -1c
.RI "Vector3 \fBposition\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
