.TH "DevionGames.CategoryAttribute" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.CategoryAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Attribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCategoryAttribute\fP (string category)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCategory\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
