.TH "DevionGames.ObjectProperty" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.ObjectProperty
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDevionGames\&.INameable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBGetValue\fP ()"
.br
.ti -1c
.RI "void \fBSetValue\fP (object value)"
.br
.ti -1c
.RI "string \fBToString\fP (string format)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBGetPropertyName\fP (Type mType)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBstringValue\fP"
.br
.ti -1c
.RI "int \fBintValue\fP"
.br
.ti -1c
.RI "float \fBfloatValue\fP"
.br
.ti -1c
.RI "Color \fBcolorValue\fP"
.br
.ti -1c
.RI "bool \fBboolValue\fP"
.br
.ti -1c
.RI "UnityEngine\&.Object \fBobjectReferenceValue\fP"
.br
.ti -1c
.RI "Vector2 \fBvector2Value\fP"
.br
.ti -1c
.RI "Vector3 \fBvector3Value\fP"
.br
.ti -1c
.RI "bool \fBshow\fP"
.br
.ti -1c
.RI "Color \fBcolor\fP = Color\&.white"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Type \fBSerializedType\fP\fC [get]\fP"
.br
.ti -1c
.RI "static Type[] \fBSupportedTypes\fP\fC [get]\fP"
.br
.ti -1c
.RI "static string[] \fBDisplayNames\fP\fC [get]\fP"
.br
.in -1c

Properties inherited from \fBDevionGames\&.INameable\fP
.SH "Property Documentation"
.PP 
.SS "string DevionGames\&.ObjectProperty\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Implements \fBDevionGames\&.INameable\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
