.TH "DevionGames.CoroutineQueue" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.CoroutineQueue
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCoroutineQueue\fP (MonoBehaviour coroutineOwner)"
.br
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBStop\fP ()"
.br
.ti -1c
.RI "void \fBEnqueueAction\fP (IEnumerator aAction)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
