.TH "DevionGames.HeaderLineAttribute" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.HeaderLineAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyAttribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHeaderLineAttribute\fP (string \fBheader\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly string \fBheader\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DevionGames\&.HeaderLineAttribute\&.HeaderLineAttribute (string header)"
Add a header above some fields in the Inspector\&.
.PP
\fBParameters\fP
.RS 4
\fIheader\fP The header text\&.
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "readonly string DevionGames\&.HeaderLineAttribute\&.header"
The header text\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
