.TH "DevionGames.UIWidgets.MenuItem" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.UIWidgets.MenuItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits Selectable, and IPointerClickHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPointerClick\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "override void \fBOnPointerEnter\fP (PointerEventData eventData)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "UnityEvent \fBonTrigger\fP\fC [get, set]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
