.TH "DevionGames.UIWidgets.NotificationOptions" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.UIWidgets.NotificationOptions \- Message options\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNotificationOptions\fP (\fBNotificationOptions\fP other)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBtitle\fP = string\&.Empty"
.br
.RI "The title to display\&. "
.ti -1c
.RI "string \fBtext\fP = string\&.Empty"
.br
.RI "The message to display\&. "
.ti -1c
.RI "Color \fBcolor\fP = Color\&.white"
.br
.RI "The color of the text\&. "
.ti -1c
.RI "Sprite \fBicon\fP"
.br
.RI "The icon to display\&. "
.ti -1c
.RI "float \fBdelay\fP = 2\&.0f"
.br
.RI "The delay before fading\&. "
.ti -1c
.RI "float \fBduration\fP = 2\&.0f"
.br
.RI "The duration of fading\&. "
.ti -1c
.RI "bool \fBignoreTimeScale\fP = true"
.br
.RI "Ignore TimeScale\&. "
.in -1c
.SH "Detailed Description"
.PP 
Message options\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
