.TH "DevionGames.UIWidgets.Tooltip" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.UIWidgets.Tooltip
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDevionGames\&.UIWidgets\&.UIWidget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBShow\fP ()"
.br
.RI "Show this widget\&. "
.ti -1c
.RI "virtual void \fBShow\fP (string text)"
.br
.ti -1c
.RI "virtual void \fBShow\fP (string title, string text)"
.br
.ti -1c
.RI "virtual void \fBShow\fP (string title, string text, Sprite icon, List< KeyValuePair< string, string > > pairs)"
.br
.ti -1c
.RI "virtual void \fBShow\fP (string title, string text, Sprite icon, List< KeyValuePair< string, string > > pairs, float width, bool showBackground)"
.br
.ti -1c
.RI "override void \fBClose\fP (UnityAction result=null)"
.br
.RI "Close this widget\&. "
.in -1c

Public Member Functions inherited from \fBDevionGames\&.UIWidgets\&.UIWidget\fP
.in +1c
.ti -1c
.RI "virtual void \fBClose\fP ()"
.br
.ti -1c
.RI "virtual IEnumerator \fBDelayedClose\fP (UnityAction result)"
.br
.ti -1c
.RI "virtual void \fBHide\fP ()"
.br
.ti -1c
.RI "virtual void \fBToggle\fP ()"
.br
.RI "Toggle the visibility of this widget\&. "
.ti -1c
.RI "virtual void \fBFocus\fP ()"
.br
.RI "Brings the widget to the top\&. "
.in -1c

Public Member Functions inherited from \fBDevionGames\&.CallbackHandler\fP
.in +1c
.ti -1c
.RI "void \fBRegisterListener\fP (string eventID, UnityAction< \fBCallbackEventData\fP > call)"
.br
.ti -1c
.RI "void \fBRemoveListener\fP (string eventID, UnityAction< \fBCallbackEventData\fP > call)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnStart\fP ()"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBUpdatePosition\fP ()"
.br
.ti -1c
.RI "virtual \fBStringPairSlot\fP \fBCreateSlot\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBDevionGames\&.UIWidgets\&.UIWidget\fP
.in +1c
.ti -1c
.RI "virtual void \fBOnAwake\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBDevionGames\&.CallbackHandler\fP
.in +1c
.ti -1c
.RI "void \fBExecute\fP (string eventID, \fBCallbackEventData\fP eventData)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBm_UpdatePosition\fP =true"
.br
.RI "Update position to follow mouse\&. "
.ti -1c
.RI "Text \fBm_Title\fP"
.br
.RI "The Text component to display tooltip title\&. "
.ti -1c
.RI "Text \fBm_Text\fP"
.br
.RI "The Text component to display tooltip text\&. "
.ti -1c
.RI "Image \fBm_Icon\fP"
.br
.RI "The Image component to display the icon\&. "
.ti -1c
.RI "Image \fBm_Background\fP"
.br
.RI "The background image\&. "
.ti -1c
.RI "\fBStringPairSlot\fP \fBm_SlotPrefab\fP"
.br
.RI "StringPairSlot prefab to display a string - string pair\&. "
.ti -1c
.RI "Canvas \fBm_Canvas\fP"
.br
.ti -1c
.RI "Transform \fBm_SlotParent\fP"
.br
.ti -1c
.RI "float \fBm_Width\fP = 300f"
.br
.ti -1c
.RI "List< \fBStringPairSlot\fP > \fBm_SlotCache\fP"
.br
.ti -1c
.RI "bool \fB_updatePosition\fP"
.br
.in -1c

Protected Attributes inherited from \fBDevionGames\&.UIWidgets\&.UIWidget\fP
.in +1c
.ti -1c
.RI "bool \fBm_DeactivateOnClose\fP = true"
.br
.RI "If true deactivates the gameobject when closed\&. "
.ti -1c
.RI "RectTransform \fBm_RectTransform\fP"
.br
.RI "The RectTransform of the widget\&. "
.ti -1c
.RI "CanvasGroup \fBm_CanvasGroup\fP"
.br
.RI "The CanvasGroup of the widget\&. "
.ti -1c
.RI "State \fBm_CurrentState\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBDevionGames\&.UIWidgets\&.UIWidget\fP
.in +1c
.ti -1c
.RI "int \fBpriority\fP"
.br
.ti -1c
.RI "AudioClip \fBshowSound\fP"
.br
.RI "The AudioClip that will be played when this widget shows\&. "
.ti -1c
.RI "AudioClip \fBcloseSound\fP"
.br
.RI "The AudioClip that will be played when this widget closes\&. "
.ti -1c
.RI "\fBWidgetEvent\fP \fBonShow\fP"
.br
.RI "Events that will be invoked when this widget is shows\&. "
.ti -1c
.RI "\fBWidgetEvent\fP \fBonClose\fP"
.br
.RI "Events that will be invoked when this widget closes\&. "
.in -1c

Public Attributes inherited from \fBDevionGames\&.CallbackHandler\fP
.in +1c
.ti -1c
.RI "List< \fBCallbackHandler\&.Entry\fP > \fBdelegates\fP"
.br
.in -1c

Protected Types inherited from \fBDevionGames\&.UIWidgets\&.UIWidget\fP
.in +1c
.ti -1c
.RI "enum \fBState\fP { \fBShowing\fP, \fBVisible\fP, \fBClosing\fP, \fBInvisible\fP }"
.br
.in -1c

Properties inherited from \fBDevionGames\&.UIWidgets\&.UIWidget\fP
.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the name\&. "
.ti -1c
.RI "override string[] \fBCallbacks\fP\fC [get]\fP"
.br
.ti -1c
.RI "State \fBIsStateVisible\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether this widget is visible\&. "
.ti -1c
.RI "bool \fBIsVisible\fP\fC [get]\fP"
.br
.in -1c

Properties inherited from \fBDevionGames\&.CallbackHandler\fP
.in +1c
.ti -1c
.RI "string[] \fBCallbacks\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void DevionGames\&.UIWidgets\&.Tooltip\&.Close (UnityAction result = \fCnull\fP)\fC [virtual]\fP"

.PP
Close this widget\&. 
.PP
Reimplemented from \fBDevionGames\&.UIWidgets\&.UIWidget\fP\&.
.SS "override void DevionGames\&.UIWidgets\&.Tooltip\&.OnStart ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBDevionGames\&.UIWidgets\&.UIWidget\fP\&.
.SS "override void DevionGames\&.UIWidgets\&.Tooltip\&.Show ()\fC [virtual]\fP"

.PP
Show this widget\&. 
.PP
Reimplemented from \fBDevionGames\&.UIWidgets\&.UIWidget\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
