.TH "DevionGames.SelectionHandler" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.SelectionHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDevionGames\&.CallbackHandler\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBSelectionInputType\fP { \fBLeftClick\fP = 1, \fBRightClick\fP = 2, \fBKey\fP = 4, \fBRaycast\fP = 8, \fBMiddleClick\fP = 16 }"
.br
.ti -1c
.RI "enum \fBDeselectionInputType\fP { \fBLeftClick\fP = 1, \fBRightClick\fP = 2, \fBKey\fP = 4, \fBDistance\fP = 8, \fBMiddleClick\fP = 16 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSelect\fP (\fBISelectable\fP selectable)"
.br
.ti -1c
.RI "void \fBDeselect\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBDevionGames\&.CallbackHandler\fP
.in +1c
.ti -1c
.RI "void \fBRegisterListener\fP (string eventID, UnityAction< \fBCallbackEventData\fP > call)"
.br
.ti -1c
.RI "void \fBRemoveListener\fP (string eventID, UnityAction< \fBCallbackEventData\fP > call)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SelectionInputType \fBselectionType\fP = SelectionInputType\&.LeftClick | SelectionInputType\&.Raycast"
.br
.ti -1c
.RI "DeselectionInputType \fBdeselectionType\fP = DeselectionInputType\&.LeftClick | DeselectionInputType\&.Key"
.br
.in -1c

Public Attributes inherited from \fBDevionGames\&.CallbackHandler\fP
.in +1c
.ti -1c
.RI "List< \fBCallbackHandler\&.Entry\fP > \fBdelegates\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string[] \fBCallbacks\fP\fC [get]\fP"
.br
.in -1c

Properties inherited from \fBDevionGames\&.CallbackHandler\fP
.in +1c
.ti -1c
.RI "string[] \fBCallbacks\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBDevionGames\&.CallbackHandler\fP
.in +1c
.ti -1c
.RI "void \fBExecute\fP (string eventID, \fBCallbackEventData\fP eventData)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
