.TH "DevionGames.INameable" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.INameable
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDevionGames\&.NamedVariable\fP, and \fBDevionGames\&.ObjectProperty\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
