.TH "DevionGames.ComponentMenu" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.ComponentMenu
.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Attribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBComponentMenu\fP (string menuName)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBcomponentMenu\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
