.TH "DevionGames.Settings" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.Settings
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBTextureQuality\fP : int { \fBFull\fP =0, \fBHalf\fP =1, \fBQuarter\fP =2, \fBEighth\fP =3 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetQualityLevel\fP (float index)"
.br
.ti -1c
.RI "void \fBSetQualityLevel\fP (int index)"
.br
.ti -1c
.RI "void \fBIncreaseQualityLevel\fP ()"
.br
.ti -1c
.RI "void \fBDecreaseQualityLevel\fP ()"
.br
.ti -1c
.RI "void \fBSetResolution\fP (int index)"
.br
.ti -1c
.RI "void \fBSetResolution\fP (int width, int height)"
.br
.ti -1c
.RI "void \fBIncreaseResolution\fP ()"
.br
.ti -1c
.RI "void \fBDecreaseResolution\fP ()"
.br
.ti -1c
.RI "void \fBSetFullscreen\fP (bool fullScreen)"
.br
.ti -1c
.RI "void \fBSetAntialiasing\fP (int value)"
.br
.ti -1c
.RI "void \fBIncreaseAntialiasing\fP ()"
.br
.ti -1c
.RI "void \fBDecreaseAntialisasing\fP ()"
.br
.ti -1c
.RI "void \fBSetTextureQuality\fP (int textureLimit)"
.br
.ti -1c
.RI "void \fBIncreaseTextureQuality\fP ()"
.br
.ti -1c
.RI "void \fBDecreaseTextureQuality\fP ()"
.br
.ti -1c
.RI "void \fBSetEffectAntialiasing\fP (bool state)"
.br
.ti -1c
.RI "void \fBSetEffectBloom\fP (bool state)"
.br
.ti -1c
.RI "void \fBSetEffectVignette\fP (bool state)"
.br
.ti -1c
.RI "void \fBSetEffectAmbient\fP (bool state)"
.br
.ti -1c
.RI "void \fBSetAllEffects\fP (bool state)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBQualityContent\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBResolutionContent\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFullscreen\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBAntialiasingContent\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBTextureQualityContent\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsStandalone\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
