.TH "DevionGames.UIWidgets.TooltipTrigger" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.UIWidgets.TooltipTrigger \- Tooltip trigger to display fixed tooltips\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, IPointerEnterHandler, and IPointerExitHandler\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStringPair\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPointerEnter\fP (PointerEventData eventData)"
.br
.RI "Called when the mouse pointer starts hovering the ui element\&. "
.ti -1c
.RI "void \fBOnPointerExit\fP (PointerEventData eventData)"
.br
.RI "Called when the mouse pointer exits the element\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBtooltipTitle\fP"
.br
.ti -1c
.RI "string \fBtooltip\fP"
.br
.RI "The text to display\&. "
.ti -1c
.RI "Sprite \fBicon\fP"
.br
.RI "Optionally show an icon\&. "
.ti -1c
.RI "\fBStringPair\fP[] \fBproperties\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tooltip trigger to display fixed tooltips\&. 
.SH "Member Function Documentation"
.PP 
.SS "void DevionGames\&.UIWidgets\&.TooltipTrigger\&.OnPointerEnter (PointerEventData eventData)"

.PP
Called when the mouse pointer starts hovering the ui element\&. 
.PP
\fBParameters\fP
.RS 4
\fIeventData\fP Event data\&.
.RE
.PP

.SS "void DevionGames\&.UIWidgets\&.TooltipTrigger\&.OnPointerExit (PointerEventData eventData)"

.PP
Called when the mouse pointer exits the element\&. 
.PP
\fBParameters\fP
.RS 4
\fIeventData\fP Event data\&.
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "string DevionGames\&.UIWidgets\&.TooltipTrigger\&.tooltipTitle"
The title to display 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
