.TH "DevionGames.AudioPlaylist" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.AudioPlaylist
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "List< AudioClip > \fBm_Clips\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "AudioClip \fBthis[int index]\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBCount\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
