.TH "DevionGames.InspectorLabelAttribute" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevionGames.InspectorLabelAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyAttribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInspectorLabelAttribute\fP (string label)"
.br
.ti -1c
.RI "\fBInspectorLabelAttribute\fP (string label, string tooltip)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly string \fBlabel\fP"
.br
.ti -1c
.RI "readonly string \fBtooltip\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
