.TH "EnvMapAnimator" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnvMapAnimator
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3 \fBRotationSpeeds\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
