.TH "Google.Impl.SignInHelperObject" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Google.Impl.SignInHelperObject \- Helper object to connect the Sign-in API to the Unity Game Scene\&. /summary> remarks>This class is added to the scene so that the \fBGoogle\fP Sign-in API can start coroutines\&. /remarks>  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SH "Detailed Description"
.PP 
Helper object to connect the Sign-in API to the Unity Game Scene\&. /summary> remarks>This class is added to the scene so that the \fBGoogle\fP Sign-in API can start coroutines\&. /remarks> 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
