.TH "Google.GoogleSignIn.SignInException" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Google.GoogleSignIn.SignInException \- Sign in exception\&. This is a checked exception for handling specific errors during the sign-in process\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSignInException\fP (\fBGoogleSignInStatusCode\fP status, string message)"
.br
.ti -1c
.RI "\fBSignInException\fP (\fBGoogleSignInStatusCode\fP status, string message, Exception innerException)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBSignInException\fP (\fBGoogleSignInStatusCode\fP status, SerializationInfo info, StreamingContext context)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBGoogleSignInStatusCode\fP \fBStatus\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Sign in exception\&. This is a checked exception for handling specific errors during the sign-in process\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
