.TH "Google.Impl" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Google.Impl
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseObject\fP"
.br
.RI "Base object manages the pointer to a native object which provides the implementation of a C# object\&. "
.ti -1c
.RI "class \fBGoogleSignInImpl\fP"
.br
.ti -1c
.RI "class \fBNativeFuture\fP"
.br
.RI "Native future is an interal class that implements the FutureAPIImpl by calling native methods which are implemented in the native code\&. "
.ti -1c
.RI "class \fBSignInHelperObject\fP"
.br
.RI "Helper object to connect the Sign-in API to the Unity Game Scene\&. /summary> remarks>This class is added to the scene so that the \fBGoogle\fP Sign-in API can start coroutines\&. /remarks> "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
