.TH "md__2_users_2diego_2_documents_2_unity_01_projects_2_achroma_01_adventure_2_assets_2_achroma_2_runtime_2_shopify_2_examples_2_q_u_i_c_k_s_t_a_r_t___t_u_t_o_r_i_a_l" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__2_users_2diego_2_documents_2_unity_01_projects_2_achroma_01_adventure_2_assets_2_achroma_2_runtime_2_shopify_2_examples_2_q_u_i_c_k_s_t_a_r_t___t_u_t_o_r_i_a_l \- Introduction 
.PP
 
.SS "Purpose of this tutorial"
The goal of this tutorial is to get an in-game shop setup as quickly as possible by leveraging the pre-built shop popup in this example project\&. For a more detailed breakdown of how the shop popup was created, and steps on creating a similar shop popup of your own, please see the \fCfull tutorial\fP\&.
.SS "Who this tutorial is for"
This tutorial is aimed at any developer looking to quickly integrate the sale of physical merchandise into their game\&. Since this tutorial uses the pre-built shop popup, only basic Unity skills are required in order to get setup\&.
.SS "Integrating the shop popup"
.SS "Add the unitypackage"
.PP
We'll start with a blank, default Unity project, as seen above\&.
.PP
Our first step is to add in the shop popup unitypackage, which can be downloaded \fChere\fP\&. Drag this into the Assets area of your project\&.
.PP
.PP
When prompted, import the package contents\&.
.SS "Add an instance of the Shop Popup prefab"
.PP
Next, go into the Prefabs folder, and drag an instance of the Shop Popup prefab into the scene\&.
.PP
In the options for the Shop Popup prefab, we can set our Access Token and Shop Domain\&. For more information on getting the Access Token, see \fCObtaining a storefront Access Token\fP\&.
.SS "Add the UI eventsystem"
.PP
In order for the UI events to fire, we must add in a UI > Eventsystem game object\&.
.SS "Test the shop popup"
.PP
With these steps completed, the shop popup should be ready to use\&. There is a hidden button which triggers the shop popup, click in the middle of the view and the shop popup should appear\&. 
