.TH "NotificationTrigger" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NotificationTrigger \- Message container example\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddRandomNotification\fP ()"
.br
.RI "Called from a button OnClick event in the example\&. "
.ti -1c
.RI "void \fBAddNotification\fP (InputField input)"
.br
.RI "Called from a button OnClick event in the example\&. "
.ti -1c
.RI "void \fBAddNotification\fP (float index)"
.br
.RI "Called from a Slider OnValueChanged event in the example\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "NotificationOptions[] \fBoptions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Message container example\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
