.TH "Shopify.Unity.GraphQL.PaymentSettingsQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.PaymentSettingsQuery \- Settings related to payments\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPaymentSettingsQuery\fP (StringBuilder query)"
.br
.RI "PaymentSettingsQuery is used to build queries\&. Typically PaymentSettingsQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBPaymentSettingsQuery\fP \fBacceptedCardBrands\fP ()"
.br
.RI "List of the card brands which the shop accepts\&. "
.ti -1c
.RI "\fBPaymentSettingsQuery\fP \fBcardVaultUrl\fP ()"
.br
.RI "The url pointing to the endpoint to vault credit cards\&. "
.ti -1c
.RI "\fBPaymentSettingsQuery\fP \fBcountryCode\fP ()"
.br
.RI "The country where the shop is located\&. "
.ti -1c
.RI "\fBPaymentSettingsQuery\fP \fBcurrencyCode\fP ()"
.br
.RI "The three-letter code for the shop's primary currency\&. "
.ti -1c
.RI "\fBPaymentSettingsQuery\fP \fBenabledPresentmentCurrencies\fP ()"
.br
.RI "A list of enabled currencies (ISO 4217 format) that the shop accepts\&. Merchants can enable currencies from their \fBShopify\fP Payments settings in the \fBShopify\fP admin\&. "
.ti -1c
.RI "\fBPaymentSettingsQuery\fP \fBshopifyPaymentsAccountId\fP ()"
.br
.RI "The shop’s \fBShopify\fP Payments account id\&. "
.ti -1c
.RI "\fBPaymentSettingsQuery\fP \fBsupportedDigitalWallets\fP ()"
.br
.RI "List of the digital wallets which the shop supports\&. "
.in -1c
.SH "Detailed Description"
.PP 
Settings related to payments\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
