.TH "Shopify.Unity.GraphQL.ArticleAuthorQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.ArticleAuthorQuery \- The author of an article\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArticleAuthorQuery\fP (StringBuilder query)"
.br
.RI "ArticleAuthorQuery is used to build queries\&. Typically ArticleAuthorQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBArticleAuthorQuery\fP \fBbio\fP ()"
.br
.RI "The author's bio\&. "
.ti -1c
.RI "\fBArticleAuthorQuery\fP \fBemail\fP ()"
.br
.RI "The author’s email\&. "
.ti -1c
.RI "\fBArticleAuthorQuery\fP \fBfirstName\fP ()"
.br
.RI "The author's first name\&. "
.ti -1c
.RI "\fBArticleAuthorQuery\fP \fBlastName\fP ()"
.br
.RI "The author's last name\&. "
.ti -1c
.RI "\fBArticleAuthorQuery\fP \fBname\fP ()"
.br
.RI "The author's full name\&. "
.in -1c
.SH "Detailed Description"
.PP 
The author of an article\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
