.TH "Shopify.Unity.CustomerAccessTokenCreateInput" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.CustomerAccessTokenCreateInput \- Specifies the input fields required to create a customer access token\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShopify\&.Unity\&.SDK\&.InputBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCustomerAccessTokenCreateInput\fP (string \fBemail\fP, string \fBpassword\fP)"
.br
.ti -1c
.RI "\fBCustomerAccessTokenCreateInput\fP (Dictionary< string, object > dataJSON)"
.br
.in -1c

Public Member Functions inherited from \fBShopify\&.Unity\&.SDK\&.InputBase\fP
.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns a string representing a GraphQL input object\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBemailFieldKey\fP = 'email'"
.br
.ti -1c
.RI "const string \fBpasswordFieldKey\fP = 'password'"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBemail\fP\fC [get, set]\fP"
.br
.RI "The email associated to the customer\&. "
.ti -1c
.RI "string \fBpassword\fP\fC [get, set]\fP"
.br
.RI "The login password to be used by the customer\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBShopify\&.Unity\&.SDK\&.InputBase\fP
.in +1c
.ti -1c
.RI "void \fBSet\fP (string key, object value)"
.br
.ti -1c
.RI "object \fBGet\fP (string key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Specifies the input fields required to create a customer access token\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Shopify\&.Unity\&.CustomerAccessTokenCreateInput\&.CustomerAccessTokenCreateInput (string email, string password)"

.PP
\fBParameters\fP
.RS 4
\fIemail\fP The email associated to the customer\&. 
.br
\fIpassword\fP The login password to be used by the customer\&. 
.RE
.PP

.SS "Shopify\&.Unity\&.CustomerAccessTokenCreateInput\&.CustomerAccessTokenCreateInput (Dictionary< string, object > dataJSON)"

.PP
\fBParameters\fP
.RS 4
\fIemail\fP The email associated to the customer\&. 
.br
\fIpassword\fP The login password to be used by the customer\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
