.TH "Shopify.Unity.GraphQL.SelectedOptionQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.SelectedOptionQuery \- Properties used by customers to select a product variant\&. Products can have multiple options, like different sizes or colors\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSelectedOptionQuery\fP (StringBuilder query)"
.br
.RI "SelectedOptionQuery is used to build queries\&. Typically SelectedOptionQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBSelectedOptionQuery\fP \fBname\fP ()"
.br
.RI "The product option’s name\&. "
.ti -1c
.RI "\fBSelectedOptionQuery\fP \fBvalue\fP ()"
.br
.RI "The product option’s value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Properties used by customers to select a product variant\&. Products can have multiple options, like different sizes or colors\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
