.TH "Shopify.Unity.GraphQL.Model3dQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.Model3dQuery \- Represents a \fBShopify\fP hosted 3D model\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModel3dQuery\fP (StringBuilder query)"
.br
.RI "Model3dQuery is used to build queries\&. Typically Model3dQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBModel3dQuery\fP \fBalt\fP ()"
.br
.RI "A word or phrase to share the nature or contents of a media\&. "
.ti -1c
.RI "\fBModel3dQuery\fP \fBid\fP ()"
.br
.RI "Globally unique identifier\&. "
.ti -1c
.RI "\fBModel3dQuery\fP \fBmediaContentType\fP ()"
.br
.RI "The media content type\&. "
.ti -1c
.RI "\fBModel3dQuery\fP \fBpreviewImage\fP (ImageDelegate buildQuery)"
.br
.RI "The preview image for the media\&. "
.ti -1c
.RI "\fBModel3dQuery\fP \fBsources\fP (Model3dSourceDelegate buildQuery)"
.br
.RI "The sources for a 3d model\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a \fBShopify\fP hosted 3D model\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
