.TH "Shopify.Unity.SDK.AliasException" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.SDK.AliasException \- This exception is thrown when trying to access a response field using an alias which was not used to build the query\&. AliasException 
.PP
is also thrown when the alias format is invalid for instance a blank string or the alias uses invalid characters\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAliasException\fP (string message)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This exception is thrown when trying to access a response field using an alias which was not used to build the query\&. AliasException 
.PP
is also thrown when the alias format is invalid for instance a blank string or the alias uses invalid characters\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
