.TH "Shopify.Unity.GraphQL.CommentAuthorQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.CommentAuthorQuery \- The author of a comment\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommentAuthorQuery\fP (StringBuilder query)"
.br
.RI "CommentAuthorQuery is used to build queries\&. Typically CommentAuthorQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBCommentAuthorQuery\fP \fBemail\fP ()"
.br
.RI "The author's email\&. "
.ti -1c
.RI "\fBCommentAuthorQuery\fP \fBname\fP ()"
.br
.RI "The author’s name\&. "
.in -1c
.SH "Detailed Description"
.PP 
The author of a comment\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
