.TH "Shopify.Examples.Panels.CartPanel" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Examples.Panels.CartPanel
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddToCart\fP (\fBProduct\fP product, \fBProductVariant\fP variant)"
.br
.ti -1c
.RI "void \fBEmptyCart\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCartQuantityChangedEvent\fP \fBOnCartQuantityChanged\fP = new \fBCartQuantityChangedEvent\fP()"
.br
.ti -1c
.RI "\fBCheckoutFailureEvent\fP \fBOnCheckoutFailure\fP = new \fBCheckoutFailureEvent\fP()"
.br
.ti -1c
.RI "UnityEvent \fBOnCheckoutSuccess\fP"
.br
.ti -1c
.RI "UnityEvent \fBOnCheckoutCancelled\fP"
.br
.ti -1c
.RI "UnityEvent \fBOnReturnToProducts\fP"
.br
.ti -1c
.RI "Button \fBBackToProductsButton\fP"
.br
.ti -1c
.RI "Button \fBCheckoutButton\fP"
.br
.ti -1c
.RI "Button \fBNativeCheckoutButton\fP"
.br
.ti -1c
.RI "Text \fBCheckoutButtonText\fP"
.br
.ti -1c
.RI "Text \fBSubtotalText\fP"
.br
.ti -1c
.RI "\fBCartPanelLineItem\fP \fBCartPanelLineItemTemplate\fP"
.br
.ti -1c
.RI "ScrollRect \fBScrollView\fP"
.br
.ti -1c
.RI "RectTransform \fBContent\fP"
.br
.ti -1c
.RI "string \fBiOSMerchantID\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
