.TH "Shopify.Unity.GraphQL.CheckoutCreatePayloadQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.CheckoutCreatePayloadQuery \- Return type for \fCcheckoutCreate\fP mutation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCheckoutCreatePayloadQuery\fP (StringBuilder query)"
.br
.RI "CheckoutCreatePayloadQuery is used to build queries\&. Typically CheckoutCreatePayloadQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBCheckoutCreatePayloadQuery\fP \fBcheckout\fP (CheckoutDelegate buildQuery)"
.br
.RI "The new checkout object\&. "
.ti -1c
.RI "\fBCheckoutCreatePayloadQuery\fP \fBcheckoutUserErrors\fP (CheckoutUserErrorDelegate buildQuery)"
.br
.RI "List of errors that occurred executing the mutation\&. "
.ti -1c
.RI "\fBCheckoutCreatePayloadQuery\fP \fBuserErrors\fP (UserErrorDelegate buildQuery)"
.br
.RI "List of errors that occurred executing the mutation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Return type for \fCcheckoutCreate\fP mutation\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBCheckoutCreatePayloadQuery\fP Shopify\&.Unity\&.GraphQL\&.CheckoutCreatePayloadQuery\&.userErrors (UserErrorDelegate buildQuery)"

.PP
List of errors that occurred executing the mutation\&. 
.PP
\fBDeprecated\fP
.RS 4
Use \fCcheckoutUserErrors\fP instead 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
