.TH "Shopify.Unity.GraphQL.CustomerAccessTokenDeletePayloadQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.CustomerAccessTokenDeletePayloadQuery \- Return type for \fCcustomerAccessTokenDelete\fP mutation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCustomerAccessTokenDeletePayloadQuery\fP (StringBuilder query)"
.br
.RI "CustomerAccessTokenDeletePayloadQuery is used to build queries\&. Typically CustomerAccessTokenDeletePayloadQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBCustomerAccessTokenDeletePayloadQuery\fP \fBdeletedAccessToken\fP ()"
.br
.RI "The destroyed access token\&. "
.ti -1c
.RI "\fBCustomerAccessTokenDeletePayloadQuery\fP \fBdeletedCustomerAccessTokenId\fP ()"
.br
.RI "ID of the destroyed customer access token\&. "
.ti -1c
.RI "\fBCustomerAccessTokenDeletePayloadQuery\fP \fBuserErrors\fP (UserErrorDelegate buildQuery)"
.br
.RI "List of errors that occurred executing the mutation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Return type for \fCcustomerAccessTokenDelete\fP mutation\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
