.TH "Shopify.Unity.OrderLineItem" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.OrderLineItem \- Represents a single line in an order\&. There is one line item for each distinct product variant\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShopify\&.Unity\&.SDK\&.AbstractResponse\fP, and ICloneable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOrderLineItem\fP (Dictionary< string, object > dataJSON)"
.br
.RI "Accepts deserialized json data\&.  Will further parse passed in data\&. "
.ti -1c
.RI "List< \fBAttribute\fP > \fBcustomAttributes\fP ()"
.br
.RI "List of custom attributes associated to the line item\&. "
.ti -1c
.RI "List< \fBDiscountAllocation\fP > \fBdiscountAllocations\fP ()"
.br
.RI "The discounts that have been allocated onto the order line item by discount applications\&. "
.ti -1c
.RI "long \fBquantity\fP ()"
.br
.RI "The number of products variants associated to the line item\&. "
.ti -1c
.RI "string \fBtitle\fP ()"
.br
.RI "The title of the product combined with title of the variant\&. "
.ti -1c
.RI "\fBProductVariant\fP \fBvariant\fP ()"
.br
.RI "The product variant object associated to the line item\&. "
.ti -1c
.RI "object \fBClone\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBShopify\&.Unity\&.SDK\&.AbstractResponse\fP
.in +1c
.ti -1c
.RI "T \fBGet< T >\fP (string field, string alias=null)"
.br
.in -1c

Protected Attributes inherited from \fBShopify\&.Unity\&.SDK\&.AbstractResponse\fP
.in +1c
.ti -1c
.RI "Dictionary< string, object > \fBData\fP"
.br
.in -1c

Properties inherited from \fBShopify\&.Unity\&.SDK\&.AbstractResponse\fP
.in +1c
.ti -1c
.RI "Dictionary< string, object > \fBDataJSON\fP\fC [get, protected set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a single line in an order\&. There is one line item for each distinct product variant\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Shopify\&.Unity\&.OrderLineItem\&.OrderLineItem (Dictionary< string, object > dataJSON)"

.PP
Accepts deserialized json data\&.  Will further parse passed in data\&. 
.PP
\fBParameters\fP
.RS 4
\fIdataJSON\fP Deserialized JSON data for OrderLineItem
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
