.TH "Shopify.Unity.GraphQL.CheckoutCustomerAssociateV2payloadQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.CheckoutCustomerAssociateV2payloadQuery \- Return type for \fCcheckoutCustomerAssociateV2\fP mutation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCheckoutCustomerAssociateV2payloadQuery\fP (StringBuilder query)"
.br
.RI "CheckoutCustomerAssociateV2payloadQuery is used to build queries\&. Typically CheckoutCustomerAssociateV2payloadQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBCheckoutCustomerAssociateV2payloadQuery\fP \fBcheckout\fP (CheckoutDelegate buildQuery)"
.br
.RI "The updated checkout object\&. "
.ti -1c
.RI "\fBCheckoutCustomerAssociateV2payloadQuery\fP \fBcheckoutUserErrors\fP (CheckoutUserErrorDelegate buildQuery)"
.br
.RI "List of errors that occurred executing the mutation\&. "
.ti -1c
.RI "\fBCheckoutCustomerAssociateV2payloadQuery\fP \fBcustomer\fP (CustomerDelegate buildQuery)"
.br
.RI "The associated customer object\&. "
.ti -1c
.RI "\fBCheckoutCustomerAssociateV2payloadQuery\fP \fBuserErrors\fP (UserErrorDelegate buildQuery)"
.br
.RI "List of errors that occurred executing the mutation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Return type for \fCcheckoutCustomerAssociateV2\fP mutation\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBCheckoutCustomerAssociateV2payloadQuery\fP Shopify\&.Unity\&.GraphQL\&.CheckoutCustomerAssociateV2payloadQuery\&.userErrors (UserErrorDelegate buildQuery)"

.PP
List of errors that occurred executing the mutation\&. 
.PP
\fBDeprecated\fP
.RS 4
Use \fCcheckoutUserErrors\fP instead 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
