.TH "Shopify.Unity.GraphQL.ProductPriceRangeQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.ProductPriceRangeQuery \- The price range of the product\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProductPriceRangeQuery\fP (StringBuilder query)"
.br
.RI "ProductPriceRangeQuery is used to build queries\&. Typically ProductPriceRangeQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBProductPriceRangeQuery\fP \fBmaxVariantPrice\fP (MoneyV2Delegate buildQuery)"
.br
.RI "The highest variant's price\&. "
.ti -1c
.RI "\fBProductPriceRangeQuery\fP \fBminVariantPrice\fP (MoneyV2Delegate buildQuery)"
.br
.RI "The lowest variant's price\&. "
.in -1c
.SH "Detailed Description"
.PP 
The price range of the product\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
