.TH "Shopify.Unity.Node" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.Node \- An object with an ID to support global identification\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBShopify\&.Unity\&.AppliedGiftCard\fP, \fBShopify\&.Unity\&.Article\fP, \fBShopify\&.Unity\&.Blog\fP, \fBShopify\&.Unity\&.Checkout\fP, \fBShopify\&.Unity\&.CheckoutLineItem\fP, \fBShopify\&.Unity\&.Collection\fP, \fBShopify\&.Unity\&.Comment\fP, \fBShopify\&.Unity\&.ExternalVideo\fP, \fBShopify\&.Unity\&.MailingAddress\fP, \fBShopify\&.Unity\&.MediaImage\fP, \fBShopify\&.Unity\&.Metafield\fP, \fBShopify\&.Unity\&.Model3d\fP, \fBShopify\&.Unity\&.Order\fP, \fBShopify\&.Unity\&.Page\fP, \fBShopify\&.Unity\&.Payment\fP, \fBShopify\&.Unity\&.Product\fP, \fBShopify\&.Unity\&.ProductOption\fP, \fBShopify\&.Unity\&.ProductVariant\fP, \fBShopify\&.Unity\&.ShopPolicy\fP, \fBShopify\&.Unity\&.UnknownNode\fP, and \fBShopify\&.Unity\&.Video\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBid\fP ()"
.br
.RI "Globally unique identifier\&. "
.in -1c
.SH "Detailed Description"
.PP 
An object with an ID to support global identification\&. 
.SH "Member Function Documentation"
.PP 
.SS "string Shopify\&.Unity\&.Node\&.id ()"

.PP
Globally unique identifier\&. 
.PP
Implemented in \fBShopify\&.Unity\&.AppliedGiftCard\fP, \fBShopify\&.Unity\&.Article\fP, \fBShopify\&.Unity\&.Blog\fP, \fBShopify\&.Unity\&.Checkout\fP, \fBShopify\&.Unity\&.CheckoutLineItem\fP, \fBShopify\&.Unity\&.Collection\fP, \fBShopify\&.Unity\&.Comment\fP, \fBShopify\&.Unity\&.ExternalVideo\fP, \fBShopify\&.Unity\&.MailingAddress\fP, \fBShopify\&.Unity\&.MediaImage\fP, \fBShopify\&.Unity\&.Metafield\fP, \fBShopify\&.Unity\&.Model3d\fP, \fBShopify\&.Unity\&.UnknownNode\fP, \fBShopify\&.Unity\&.Order\fP, \fBShopify\&.Unity\&.Page\fP, \fBShopify\&.Unity\&.Payment\fP, \fBShopify\&.Unity\&.Product\fP, \fBShopify\&.Unity\&.ProductOption\fP, \fBShopify\&.Unity\&.ProductVariant\fP, \fBShopify\&.Unity\&.ShopPolicy\fP, and \fBShopify\&.Unity\&.Video\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
