.TH "Shopify.Unity.Order" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.Order \- An order is a customer’s completed request to purchase one or more products from a shop\&. An order is created when a customer completes the checkout process, during which time they provides an email address, billing address and payment information\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShopify\&.Unity\&.SDK\&.AbstractResponse\fP, ICloneable, and \fBShopify\&.Unity\&.Node\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOrder\fP (Dictionary< string, object > dataJSON)"
.br
.RI "Accepts deserialized json data\&.  Will further parse passed in data\&. "
.ti -1c
.RI "\fBCurrencyCode\fP \fBcurrencyCode\fP ()"
.br
.RI "The code of the currency used for the payment\&. "
.ti -1c
.RI "string \fBcustomerLocale\fP ()"
.br
.RI "The locale code in which this specific order happened\&. "
.ti -1c
.RI "string \fBcustomerUrl\fP ()"
.br
.RI "The unique URL that the customer can use to access the order\&. "
.ti -1c
.RI "\fBDiscountApplicationConnection\fP \fBdiscountApplications\fP (string alias=null)"
.br
.RI "Discounts that have been applied on the order\&. "
.ti -1c
.RI "string \fBemail\fP ()"
.br
.RI "The customer's email address\&. "
.ti -1c
.RI "string \fBid\fP ()"
.br
.RI "Globally unique identifier\&. "
.ti -1c
.RI "\fBOrderLineItemConnection\fP \fBlineItems\fP (string alias=null)"
.br
.RI "List of the order’s line items\&. "
.ti -1c
.RI "string \fBname\fP ()"
.br
.RI "Unique identifier for the order that appears on the order\&. For example, _#1000_ or _Store1001\&. "
.ti -1c
.RI "long \fBorderNumber\fP ()"
.br
.RI "A unique numeric identifier for the order for use by shop owner and customer\&. "
.ti -1c
.RI "string \fBphone\fP ()"
.br
.RI "The customer's phone number for receiving SMS notifications\&. "
.ti -1c
.RI "DateTime? \fBprocessedAt\fP ()"
.br
.RI "The date and time when the order was imported\&. This value can be set to dates in the past when importing from other systems\&. If no value is provided, it will be auto-generated based on current date and time\&. "
.ti -1c
.RI "\fBMailingAddress\fP \fBshippingAddress\fP ()"
.br
.RI "The address to where the order will be shipped\&. "
.ti -1c
.RI "List< \fBDiscountAllocation\fP > \fBshippingDiscountAllocations\fP ()"
.br
.RI "The discounts that have been allocated onto the shipping line by discount applications\&. "
.ti -1c
.RI "string \fBstatusUrl\fP ()"
.br
.RI "The unique URL for the order's status page\&. "
.ti -1c
.RI "decimal \fBsubtotalPrice\fP ()"
.br
.RI "Price of the order before shipping and taxes\&. "
.ti -1c
.RI "\fBMoneyV2\fP \fBsubtotalPriceV2\fP ()"
.br
.RI "Price of the order before duties, shipping and taxes\&. "
.ti -1c
.RI "List< \fBFulfillment\fP > \fBsuccessfulFulfillments\fP (string alias=null)"
.br
.RI "List of the order’s successful fulfillments\&. "
.ti -1c
.RI "decimal \fBtotalPrice\fP ()"
.br
.RI "The sum of all the prices of all the items in the order, taxes and discounts included (must be positive)\&. "
.ti -1c
.RI "\fBMoneyV2\fP \fBtotalPriceV2\fP ()"
.br
.RI "The sum of all the prices of all the items in the order, duties, taxes and discounts included (must be positive)\&. "
.ti -1c
.RI "decimal \fBtotalRefunded\fP ()"
.br
.RI "The total amount that has been refunded\&. "
.ti -1c
.RI "\fBMoneyV2\fP \fBtotalRefundedV2\fP ()"
.br
.RI "The total amount that has been refunded\&. "
.ti -1c
.RI "decimal \fBtotalShippingPrice\fP ()"
.br
.RI "The total cost of shipping\&. "
.ti -1c
.RI "\fBMoneyV2\fP \fBtotalShippingPriceV2\fP ()"
.br
.RI "The total cost of shipping\&. "
.ti -1c
.RI "decimal \fBtotalTax\fP ()"
.br
.RI "The total cost of taxes\&. "
.ti -1c
.RI "\fBMoneyV2\fP \fBtotalTaxV2\fP ()"
.br
.RI "The total cost of taxes\&. "
.ti -1c
.RI "object \fBClone\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBShopify\&.Unity\&.SDK\&.AbstractResponse\fP
.in +1c
.ti -1c
.RI "T \fBGet< T >\fP (string field, string alias=null)"
.br
.in -1c

Protected Attributes inherited from \fBShopify\&.Unity\&.SDK\&.AbstractResponse\fP
.in +1c
.ti -1c
.RI "Dictionary< string, object > \fBData\fP"
.br
.in -1c

Properties inherited from \fBShopify\&.Unity\&.SDK\&.AbstractResponse\fP
.in +1c
.ti -1c
.RI "Dictionary< string, object > \fBDataJSON\fP\fC [get, protected set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An order is a customer’s completed request to purchase one or more products from a shop\&. An order is created when a customer completes the checkout process, during which time they provides an email address, billing address and payment information\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Shopify\&.Unity\&.Order\&.Order (Dictionary< string, object > dataJSON)"

.PP
Accepts deserialized json data\&.  Will further parse passed in data\&. 
.PP
\fBParameters\fP
.RS 4
\fIdataJSON\fP Deserialized JSON data for Order
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBDiscountApplicationConnection\fP Shopify\&.Unity\&.Order\&.discountApplications (string alias = \fCnull\fP)"

.PP
Discounts that have been applied on the order\&. 
.PP
\fBParameters\fP
.RS 4
\fIalias\fP If the original field queried was queried using an alias, then pass the matching string\&. 
.RE
.PP

.SS "string Shopify\&.Unity\&.Order\&.id ()"

.PP
Globally unique identifier\&. 
.PP
Implements \fBShopify\&.Unity\&.Node\fP\&.
.SS "\fBOrderLineItemConnection\fP Shopify\&.Unity\&.Order\&.lineItems (string alias = \fCnull\fP)"

.PP
List of the order’s line items\&. 
.PP
\fBParameters\fP
.RS 4
\fIalias\fP If the original field queried was queried using an alias, then pass the matching string\&. 
.RE
.PP

.SS "decimal Shopify\&.Unity\&.Order\&.subtotalPrice ()"

.PP
Price of the order before shipping and taxes\&. 
.PP
\fBDeprecated\fP
.RS 4
Use \fCsubtotalPriceV2\fP instead 
.RE
.PP

.SS "List< \fBFulfillment\fP > Shopify\&.Unity\&.Order\&.successfulFulfillments (string alias = \fCnull\fP)"

.PP
List of the order’s successful fulfillments\&. 
.PP
\fBParameters\fP
.RS 4
\fIalias\fP If the original field queried was queried using an alias, then pass the matching string\&. 
.RE
.PP

.SS "decimal Shopify\&.Unity\&.Order\&.totalPrice ()"

.PP
The sum of all the prices of all the items in the order, taxes and discounts included (must be positive)\&. 
.PP
\fBDeprecated\fP
.RS 4
Use \fCtotalPriceV2\fP instead 
.RE
.PP

.SS "decimal Shopify\&.Unity\&.Order\&.totalRefunded ()"

.PP
The total amount that has been refunded\&. 
.PP
\fBDeprecated\fP
.RS 4
Use \fCtotalRefundedV2\fP instead 
.RE
.PP

.SS "decimal Shopify\&.Unity\&.Order\&.totalShippingPrice ()"

.PP
The total cost of shipping\&. 
.PP
\fBDeprecated\fP
.RS 4
Use \fCtotalShippingPriceV2\fP instead 
.RE
.PP

.SS "decimal Shopify\&.Unity\&.Order\&.totalTax ()"

.PP
The total cost of taxes\&. 
.PP
\fBDeprecated\fP
.RS 4
Use \fCtotalTaxV2\fP instead 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
