.TH "Shopify.Unity.GraphQL.AutomaticDiscountApplicationQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.AutomaticDiscountApplicationQuery \- Automatic discount applications capture the intentions of a discount that was automatically applied\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAutomaticDiscountApplicationQuery\fP (StringBuilder query)"
.br
.RI "AutomaticDiscountApplicationQuery is used to build queries\&. Typically AutomaticDiscountApplicationQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBAutomaticDiscountApplicationQuery\fP \fBallocationMethod\fP ()"
.br
.RI "The method by which the discount's value is allocated to its entitled items\&. "
.ti -1c
.RI "\fBAutomaticDiscountApplicationQuery\fP \fBtargetSelection\fP ()"
.br
.RI "Which lines of targetType that the discount is allocated over\&. "
.ti -1c
.RI "\fBAutomaticDiscountApplicationQuery\fP \fBtargetType\fP ()"
.br
.RI "The type of line that the discount is applicable towards\&. "
.ti -1c
.RI "\fBAutomaticDiscountApplicationQuery\fP \fBtitle\fP ()"
.br
.RI "The title of the application\&. "
.ti -1c
.RI "\fBAutomaticDiscountApplicationQuery\fP \fBvalue\fP (PricingValueDelegate buildQuery)"
.br
.RI "The value of the discount application\&. "
.in -1c
.SH "Detailed Description"
.PP 
Automatic discount applications capture the intentions of a discount that was automatically applied\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
