.TH "Shopify.Unity.GraphQL.ShippingRateQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.ShippingRateQuery \- A shipping rate to be applied to a checkout\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShippingRateQuery\fP (StringBuilder query)"
.br
.RI "ShippingRateQuery is used to build queries\&. Typically ShippingRateQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBShippingRateQuery\fP \fBhandle\fP ()"
.br
.RI "Human-readable unique identifier for this shipping rate\&. "
.ti -1c
.RI "\fBShippingRateQuery\fP \fBprice\fP ()"
.br
.RI "Price of this shipping rate\&. "
.ti -1c
.RI "\fBShippingRateQuery\fP \fBpriceV2\fP (MoneyV2Delegate buildQuery)"
.br
.RI "Price of this shipping rate\&. "
.ti -1c
.RI "\fBShippingRateQuery\fP \fBtitle\fP ()"
.br
.RI "Title of this shipping rate\&. "
.in -1c
.SH "Detailed Description"
.PP 
A shipping rate to be applied to a checkout\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBShippingRateQuery\fP Shopify\&.Unity\&.GraphQL\&.ShippingRateQuery\&.price ()"

.PP
Price of this shipping rate\&. 
.PP
\fBDeprecated\fP
.RS 4
Use \fCpriceV2\fP instead 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
