.TH "Shopify.Unity.GraphQL.CustomerAddressUpdatePayloadQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.CustomerAddressUpdatePayloadQuery \- Return type for \fCcustomerAddressUpdate\fP mutation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCustomerAddressUpdatePayloadQuery\fP (StringBuilder query)"
.br
.RI "CustomerAddressUpdatePayloadQuery is used to build queries\&. Typically CustomerAddressUpdatePayloadQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBCustomerAddressUpdatePayloadQuery\fP \fBcustomerAddress\fP (MailingAddressDelegate buildQuery)"
.br
.RI "The customer’s updated mailing address\&. "
.ti -1c
.RI "\fBCustomerAddressUpdatePayloadQuery\fP \fBcustomerUserErrors\fP (CustomerUserErrorDelegate buildQuery)"
.br
.RI "List of errors that occurred executing the mutation\&. "
.ti -1c
.RI "\fBCustomerAddressUpdatePayloadQuery\fP \fBuserErrors\fP (UserErrorDelegate buildQuery)"
.br
.RI "List of errors that occurred executing the mutation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Return type for \fCcustomerAddressUpdate\fP mutation\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBCustomerAddressUpdatePayloadQuery\fP Shopify\&.Unity\&.GraphQL\&.CustomerAddressUpdatePayloadQuery\&.userErrors (UserErrorDelegate buildQuery)"

.PP
List of errors that occurred executing the mutation\&. 
.PP
\fBDeprecated\fP
.RS 4
Use \fCcustomerUserErrors\fP instead 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
