.TH "Shopify.Unity.SDK.DefaultCollectionQueries" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.SDK.DefaultCollectionQueries \- Generates default queries for ShopifyClient\&.collections 
.PP
\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShopCollections\fP (\fBQueryRootQuery\fP query, Dictionary< string, int > imageResolutions, int first=250, string after=null)"
.br
.ti -1c
.RI "void \fBCollection\fP (\fBCollectionQuery\fP collection, Dictionary< string, int > imageResolutions)"
.br
.ti -1c
.RI "void \fBProductConnection\fP (\fBProductConnectionQuery\fP productConnection)"
.br
.ti -1c
.RI "void \fBProduct\fP (\fBProductQuery\fP product)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generates default queries for ShopifyClient\&.collections 
.PP
\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
