.TH "Shopify.Unity.GraphQL.AppliedGiftCardQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.AppliedGiftCardQuery \- Details about the gift card used on the checkout\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAppliedGiftCardQuery\fP (StringBuilder query)"
.br
.RI "AppliedGiftCardQuery is used to build queries\&. Typically AppliedGiftCardQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBAppliedGiftCardQuery\fP \fBamountUsed\fP ()"
.br
.RI "The amount that was taken from the gift card by applying it\&. "
.ti -1c
.RI "\fBAppliedGiftCardQuery\fP \fBamountUsedV2\fP (MoneyV2Delegate buildQuery)"
.br
.RI "The amount that was taken from the gift card by applying it\&. "
.ti -1c
.RI "\fBAppliedGiftCardQuery\fP \fBbalance\fP ()"
.br
.RI "The amount left on the gift card\&. "
.ti -1c
.RI "\fBAppliedGiftCardQuery\fP \fBbalanceV2\fP (MoneyV2Delegate buildQuery)"
.br
.RI "The amount left on the gift card\&. "
.ti -1c
.RI "\fBAppliedGiftCardQuery\fP \fBid\fP ()"
.br
.RI "Globally unique identifier\&. "
.ti -1c
.RI "\fBAppliedGiftCardQuery\fP \fBlastCharacters\fP ()"
.br
.RI "The last characters of the gift card\&. "
.ti -1c
.RI "\fBAppliedGiftCardQuery\fP \fBpresentmentAmountUsed\fP (MoneyV2Delegate buildQuery)"
.br
.RI "The amount that was applied to the checkout in its currency\&. "
.in -1c
.SH "Detailed Description"
.PP 
Details about the gift card used on the checkout\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBAppliedGiftCardQuery\fP Shopify\&.Unity\&.GraphQL\&.AppliedGiftCardQuery\&.amountUsed ()"

.PP
The amount that was taken from the gift card by applying it\&. 
.PP
\fBDeprecated\fP
.RS 4
Use \fCamountUsedV2\fP instead 
.RE
.PP

.SS "\fBAppliedGiftCardQuery\fP Shopify\&.Unity\&.GraphQL\&.AppliedGiftCardQuery\&.balance ()"

.PP
The amount left on the gift card\&. 
.PP
\fBDeprecated\fP
.RS 4
Use \fCbalanceV2\fP instead 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
