.TH "Shopify.Unity.SDK.CastUtils" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.SDK.CastUtils
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static T \fBGetEnumValue< T >\fP (object jsonValue)"
.br
.ti -1c
.RI "static T \fBCastList< T >\fP (IList list)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static T Shopify\&.Unity\&.SDK\&.CastUtils\&.GetEnumValue< T > (object jsonValue)\fC [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIstruct\fP
.TP
\fIT\fP : \fIIConvertible\fP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
