.TH "Shopify.Unity.SDK.InputBase" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.SDK.InputBase \- Base class for all GraphQL query generator input objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBShopify\&.Unity\&.AttributeInput\fP, \fBShopify\&.Unity\&.CheckoutAttributesUpdateInput\fP, \fBShopify\&.Unity\&.CheckoutAttributesUpdateV2input\fP, \fBShopify\&.Unity\&.CheckoutCreateInput\fP, \fBShopify\&.Unity\&.CheckoutLineItemInput\fP, \fBShopify\&.Unity\&.CheckoutLineItemUpdateInput\fP, \fBShopify\&.Unity\&.CreditCardPaymentInput\fP, \fBShopify\&.Unity\&.CreditCardPaymentInputV2\fP, \fBShopify\&.Unity\&.CustomerAccessTokenCreateInput\fP, \fBShopify\&.Unity\&.CustomerActivateInput\fP, \fBShopify\&.Unity\&.CustomerCreateInput\fP, \fBShopify\&.Unity\&.CustomerResetInput\fP, \fBShopify\&.Unity\&.CustomerUpdateInput\fP, \fBShopify\&.Unity\&.MailingAddressInput\fP, \fBShopify\&.Unity\&.MoneyInput\fP, \fBShopify\&.Unity\&.SelectedOptionInput\fP, \fBShopify\&.Unity\&.TokenizedPaymentInput\fP, and \fBShopify\&.Unity\&.TokenizedPaymentInputV2\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns a string representing a GraphQL input object\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSet\fP (string key, object value)"
.br
.ti -1c
.RI "object \fBGet\fP (string key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for all GraphQL query generator input objects\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
