.TH "Shopify.Unity.SDK.DefaultShopQueries" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.SDK.DefaultShopQueries \- Generates default queries for ShopifyClient
.PP
\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPaymentSettings\fP (\fBQueryRootQuery\fP query)"
.br
.ti -1c
.RI "void \fBName\fP (\fBQueryRootQuery\fP query)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generates default queries for ShopifyClient
.PP
\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
