.TH "Shopify.Unity.GraphQL.Model3dSourceQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.Model3dSourceQuery \- Represents a source for a \fBShopify\fP hosted 3d model\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModel3dSourceQuery\fP (StringBuilder query)"
.br
.RI "Model3dSourceQuery is used to build queries\&. Typically Model3dSourceQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBModel3dSourceQuery\fP \fBfilesize\fP ()"
.br
.RI "The filesize of the 3d model\&. "
.ti -1c
.RI "\fBModel3dSourceQuery\fP \fBformat\fP ()"
.br
.RI "The format of the 3d model\&. "
.ti -1c
.RI "\fBModel3dSourceQuery\fP \fBmimeType\fP ()"
.br
.RI "The MIME type of the 3d model\&. "
.ti -1c
.RI "\fBModel3dSourceQuery\fP \fBurl\fP ()"
.br
.RI "The URL of the 3d model\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a source for a \fBShopify\fP hosted 3d model\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
