.TH "Shopify.Unity.GraphQL.DiscountCodeApplicationQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.DiscountCodeApplicationQuery \- Discount code applications capture the intentions of a discount code at the time that it is applied\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDiscountCodeApplicationQuery\fP (StringBuilder query)"
.br
.RI "DiscountCodeApplicationQuery is used to build queries\&. Typically DiscountCodeApplicationQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBDiscountCodeApplicationQuery\fP \fBallocationMethod\fP ()"
.br
.RI "The method by which the discount's value is allocated to its entitled items\&. "
.ti -1c
.RI "\fBDiscountCodeApplicationQuery\fP \fBapplicable\fP ()"
.br
.RI "Specifies whether the discount code was applied successfully\&. "
.ti -1c
.RI "\fBDiscountCodeApplicationQuery\fP \fBcode\fP ()"
.br
.RI "The string identifying the discount code that was used at the time of application\&. "
.ti -1c
.RI "\fBDiscountCodeApplicationQuery\fP \fBtargetSelection\fP ()"
.br
.RI "Which lines of targetType that the discount is allocated over\&. "
.ti -1c
.RI "\fBDiscountCodeApplicationQuery\fP \fBtargetType\fP ()"
.br
.RI "The type of line that the discount is applicable towards\&. "
.ti -1c
.RI "\fBDiscountCodeApplicationQuery\fP \fBvalue\fP (PricingValueDelegate buildQuery)"
.br
.RI "The value of the discount application\&. "
.in -1c
.SH "Detailed Description"
.PP 
Discount code applications capture the intentions of a discount code at the time that it is applied\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
