.TH "Shopify.Unity.GraphQL.CreditCardQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.CreditCardQuery \- Credit card information used for a payment\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCreditCardQuery\fP (StringBuilder query)"
.br
.RI "CreditCardQuery is used to build queries\&. Typically CreditCardQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBCreditCardQuery\fP \fBbrand\fP ()"
.br
.RI "The brand of the credit card\&. "
.ti -1c
.RI "\fBCreditCardQuery\fP \fBexpiryMonth\fP ()"
.br
.RI "The expiry month of the credit card\&. "
.ti -1c
.RI "\fBCreditCardQuery\fP \fBexpiryYear\fP ()"
.br
.RI "The expiry year of the credit card\&. "
.ti -1c
.RI "\fBCreditCardQuery\fP \fBfirstDigits\fP ()"
.br
.RI "The credit card's BIN number\&. "
.ti -1c
.RI "\fBCreditCardQuery\fP \fBfirstName\fP ()"
.br
.RI "The first name of the card holder\&. "
.ti -1c
.RI "\fBCreditCardQuery\fP \fBlastDigits\fP ()"
.br
.RI "The last 4 digits of the credit card\&. "
.ti -1c
.RI "\fBCreditCardQuery\fP \fBlastName\fP ()"
.br
.RI "The last name of the card holder\&. "
.ti -1c
.RI "\fBCreditCardQuery\fP \fBmaskedNumber\fP ()"
.br
.RI "The masked credit card number with only the last 4 digits displayed\&. "
.in -1c
.SH "Detailed Description"
.PP 
Credit card information used for a payment\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
