.TH "Shopify.Unity.SDK.NativeMessage" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.SDK.NativeMessage
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNativeMessage\fP (string identifier, string content)"
.br
.ti -1c
.RI "void \fBRespond\fP (string message)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBNativeMessage\fP \fBCreateFromJSON\fP (string jsonString)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBIdentifier\fP"
.br
.ti -1c
.RI "string \fBContent\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
