.TH "Shopify.Unity.ShippingFields" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.ShippingFields \- Wraps around a shipping address and shipping identifier\&. Used for sending the final checkout fields in one GraphQL query\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShippingFields\fP (\fBMailingAddressInput\fP shippingAddress, string shippingIdentifier)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMailingAddressInput\fP \fBShippingAddress\fP"
.br
.ti -1c
.RI "string \fBShippingIdentifier\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Wraps around a shipping address and shipping identifier\&. Used for sending the final checkout fields in one GraphQL query\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
