.TH "Shopify.Unity.SDK.NoQueryException" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.SDK.NoQueryException \- This exception is thrown when a field was accessed from a query response but the field was not queried\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNoQueryException\fP (string message)"
.br
.ti -1c
.RI "\fBNoQueryException\fP (string message, Exception innerException)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This exception is thrown when a field was accessed from a query response but the field was not queried\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
