.TH "Shopify.Unity.SDK.DefaultQueries" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.SDK.DefaultQueries \- Generates default queries for ShopifyClient\&.products 
.PP
and ShopifyClient\&.collections 
.PP
\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBGetAliasFromIndex\fP (int idx)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly int \fBMaxPageSize\fP = 250"
.br
.ti -1c
.RI "static readonly int \fBMaxProductPageSize\fP = 10"
.br
.ti -1c
.RI "static readonly int \fBMaxCollectionsPageSize\fP = 40"
.br
.ti -1c
.RI "static \fBDefaultProductQueries\fP \fBproducts\fP = new \fBDefaultProductQueries\fP()"
.br
.ti -1c
.RI "static \fBDefaultCollectionQueries\fP \fBcollections\fP = new \fBDefaultCollectionQueries\fP()"
.br
.ti -1c
.RI "static \fBDefaultCheckoutQueries\fP \fBcheckout\fP = new \fBDefaultCheckoutQueries\fP()"
.br
.ti -1c
.RI "static \fBDefaultShopQueries\fP \fBshop\fP = new \fBDefaultShopQueries\fP()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generates default queries for ShopifyClient\&.products 
.PP
and ShopifyClient\&.collections 
.PP
\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
