.TH "Shopify.Examples.Panels.ErrorPanel" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Examples.Panels.ErrorPanel
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBErrorMessage\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
