.TH "Shopify.Examples.Panels.AddProductToCartEvent" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Examples.Panels.AddProductToCartEvent
.SH SYNOPSIS
.br
.PP
.PP
Inherits UnityEvent< Shopify\&.Unity\&.Product, Shopify\&.Unity\&.ProductVariant >\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
