.TH "Shopify.Unity.SDK.ILoaderProvider" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.SDK.ILoaderProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBShopify\&.Unity\&.SDK\&.UnityLoaderProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseLoader\fP \fBGetLoader\fP (string accessToken, string domain)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
