.TH "Shopify.Unity.GraphQL.ApiVersionQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.ApiVersionQuery \- A version of the API\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBApiVersionQuery\fP (StringBuilder query)"
.br
.RI "ApiVersionQuery is used to build queries\&. Typically ApiVersionQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBApiVersionQuery\fP \fBdisplayName\fP ()"
.br
.RI "The human-readable name of the version\&. "
.ti -1c
.RI "\fBApiVersionQuery\fP \fBhandle\fP ()"
.br
.RI "The unique identifier of an ApiVersion\&. All supported API versions have a date-based (YYYY-MM) or \fCunstable\fP handle\&. "
.ti -1c
.RI "\fBApiVersionQuery\fP \fBsupported\fP ()"
.br
.RI "Whether the version is supported by \fBShopify\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
A version of the API\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
