.TH "Shopify.Unity.SDK.WebCheckoutMessageReceiver" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.SDK.WebCheckoutMessageReceiver
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP (\fBShopifyClient\fP client, \fBCheckout\fP currentCheckout, CheckoutSuccessCallback onSuccess, CheckoutCancelCallback onCancelled, CheckoutFailureCallback onFailure)"
.br
.ti -1c
.RI "void \fBOnNativeMessage\fP (string jsonMessage)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBShopifyClient\fP \fBClient\fP"
.br
.ti -1c
.RI "\fBCheckout\fP \fBCurrentCheckout\fP"
.br
.ti -1c
.RI "CheckoutSuccessCallback \fBOnSuccess\fP"
.br
.ti -1c
.RI "CheckoutCancelCallback \fBOnCancelled\fP"
.br
.ti -1c
.RI "CheckoutFailureCallback \fBOnFailure\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
