.TH "Shopify.Unity.CreditCardPaymentInput" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.CreditCardPaymentInput \- Specifies the fields required to complete a checkout with a \fBShopify\fP vaulted credit card payment\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShopify\&.Unity\&.SDK\&.InputBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCreditCardPaymentInput\fP (decimal \fBamount\fP, string \fBidempotencyKey\fP, \fBMailingAddressInput\fP \fBbillingAddress\fP, string \fBvaultId\fP, bool? \fBtest\fP=null)"
.br
.ti -1c
.RI "\fBCreditCardPaymentInput\fP (Dictionary< string, object > dataJSON)"
.br
.in -1c

Public Member Functions inherited from \fBShopify\&.Unity\&.SDK\&.InputBase\fP
.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns a string representing a GraphQL input object\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBamountFieldKey\fP = 'amount'"
.br
.ti -1c
.RI "const string \fBidempotencyKeyFieldKey\fP = 'idempotencyKey'"
.br
.ti -1c
.RI "const string \fBbillingAddressFieldKey\fP = 'billingAddress'"
.br
.ti -1c
.RI "const string \fBvaultIdFieldKey\fP = 'vaultId'"
.br
.ti -1c
.RI "const string \fBtestFieldKey\fP = 'test'"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "decimal \fBamount\fP\fC [get, set]\fP"
.br
.RI "The amount of the payment\&. "
.ti -1c
.RI "string \fBidempotencyKey\fP\fC [get, set]\fP"
.br
.RI "A unique client generated key used to avoid duplicate charges\&. When a duplicate payment is found, the original is returned instead of creating a new one\&. "
.ti -1c
.RI "\fBMailingAddressInput\fP \fBbillingAddress\fP\fC [get, set]\fP"
.br
.RI "The billing address for the payment\&. "
.ti -1c
.RI "string \fBvaultId\fP\fC [get, set]\fP"
.br
.RI "The ID returned by \fBShopify\fP's Card Vault\&. "
.ti -1c
.RI "bool? \fBtest\fP\fC [get, set]\fP"
.br
.RI "Executes the payment in test mode if possible\&. Defaults to \fCfalse\fP\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBShopify\&.Unity\&.SDK\&.InputBase\fP
.in +1c
.ti -1c
.RI "void \fBSet\fP (string key, object value)"
.br
.ti -1c
.RI "object \fBGet\fP (string key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Specifies the fields required to complete a checkout with a \fBShopify\fP vaulted credit card payment\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Shopify\&.Unity\&.CreditCardPaymentInput\&.CreditCardPaymentInput (decimal amount, string idempotencyKey, \fBMailingAddressInput\fP billingAddress, string vaultId, bool? test = \fCnull\fP)"

.PP
\fBParameters\fP
.RS 4
\fIamount\fP The amount of the payment\&. 
.br
\fIidempotencyKey\fP A unique client generated key used to avoid duplicate charges\&. When a duplicate payment is found, the original is returned instead of creating a new one\&. 
.br
\fIbillingAddress\fP The billing address for the payment\&. 
.br
\fIvaultId\fP The ID returned by \fBShopify\fP's Card Vault\&. 
.br
\fItest\fP Executes the payment in test mode if possible\&. Defaults to \fCfalse\fP\&. 
.RE
.PP

.SS "Shopify\&.Unity\&.CreditCardPaymentInput\&.CreditCardPaymentInput (Dictionary< string, object > dataJSON)"

.PP
\fBParameters\fP
.RS 4
\fIamount\fP The amount of the payment\&. 
.br
\fIidempotencyKey\fP A unique client generated key used to avoid duplicate charges\&. When a duplicate payment is found, the original is returned instead of creating a new one\&. 
.br
\fIbillingAddress\fP The billing address for the payment\&. 
.br
\fIvaultId\fP The ID returned by \fBShopify\fP's Card Vault\&. 
.br
\fItest\fP Executes the payment in test mode if possible\&. Defaults to \fCfalse\fP\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
