.TH "Shopify.Unity.GraphQL.NodeQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.NodeQuery \- An object with an ID to support global identification\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNodeQuery\fP (StringBuilder query)"
.br
.RI "NodeQuery is used to build queries\&. Typically NodeQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBid\fP ()"
.br
.RI "Globally unique identifier\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBonAppliedGiftCard\fP (AppliedGiftCardDelegate buildQuery)"
.br
.RI "will allow you to write queries on AppliedGiftCard\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBonArticle\fP (ArticleDelegate buildQuery)"
.br
.RI "will allow you to write queries on Article\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBonBlog\fP (BlogDelegate buildQuery)"
.br
.RI "will allow you to write queries on Blog\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBonCheckout\fP (CheckoutDelegate buildQuery)"
.br
.RI "will allow you to write queries on Checkout\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBonCheckoutLineItem\fP (CheckoutLineItemDelegate buildQuery)"
.br
.RI "will allow you to write queries on CheckoutLineItem\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBonCollection\fP (CollectionDelegate buildQuery)"
.br
.RI "will allow you to write queries on Collection\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBonComment\fP (CommentDelegate buildQuery)"
.br
.RI "will allow you to write queries on Comment\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBonExternalVideo\fP (ExternalVideoDelegate buildQuery)"
.br
.RI "will allow you to write queries on ExternalVideo\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBonMailingAddress\fP (MailingAddressDelegate buildQuery)"
.br
.RI "will allow you to write queries on MailingAddress\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBonMediaImage\fP (MediaImageDelegate buildQuery)"
.br
.RI "will allow you to write queries on MediaImage\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBonMetafield\fP (MetafieldDelegate buildQuery)"
.br
.RI "will allow you to write queries on Metafield\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBonModel3d\fP (Model3dDelegate buildQuery)"
.br
.RI "will allow you to write queries on Model3d\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBonOrder\fP (OrderDelegate buildQuery)"
.br
.RI "will allow you to write queries on Order\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBonPage\fP (PageDelegate buildQuery)"
.br
.RI "will allow you to write queries on Page\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBonPayment\fP (PaymentDelegate buildQuery)"
.br
.RI "will allow you to write queries on Payment\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBonProduct\fP (ProductDelegate buildQuery)"
.br
.RI "will allow you to write queries on Product\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBonProductOption\fP (ProductOptionDelegate buildQuery)"
.br
.RI "will allow you to write queries on ProductOption\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBonProductVariant\fP (ProductVariantDelegate buildQuery)"
.br
.RI "will allow you to write queries on ProductVariant\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBonShopPolicy\fP (ShopPolicyDelegate buildQuery)"
.br
.RI "will allow you to write queries on ShopPolicy\&. "
.ti -1c
.RI "\fBNodeQuery\fP \fBonVideo\fP (VideoDelegate buildQuery)"
.br
.RI "will allow you to write queries on Video\&. "
.in -1c
.SH "Detailed Description"
.PP 
An object with an ID to support global identification\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
