.TH "Shopify.Unity.CustomerActivateInput" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.CustomerActivateInput \- Specifies the input fields required to activate a customer\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShopify\&.Unity\&.SDK\&.InputBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCustomerActivateInput\fP (string \fBactivationToken\fP, string \fBpassword\fP)"
.br
.ti -1c
.RI "\fBCustomerActivateInput\fP (Dictionary< string, object > dataJSON)"
.br
.in -1c

Public Member Functions inherited from \fBShopify\&.Unity\&.SDK\&.InputBase\fP
.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns a string representing a GraphQL input object\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBactivationTokenFieldKey\fP = 'activationToken'"
.br
.ti -1c
.RI "const string \fBpasswordFieldKey\fP = 'password'"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBactivationToken\fP\fC [get, set]\fP"
.br
.RI "The activation token required to activate the customer\&. "
.ti -1c
.RI "string \fBpassword\fP\fC [get, set]\fP"
.br
.RI "New password that will be set during activation\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBShopify\&.Unity\&.SDK\&.InputBase\fP
.in +1c
.ti -1c
.RI "void \fBSet\fP (string key, object value)"
.br
.ti -1c
.RI "object \fBGet\fP (string key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Specifies the input fields required to activate a customer\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Shopify\&.Unity\&.CustomerActivateInput\&.CustomerActivateInput (string activationToken, string password)"

.PP
\fBParameters\fP
.RS 4
\fIactivationToken\fP The activation token required to activate the customer\&. 
.br
\fIpassword\fP New password that will be set during activation\&. 
.RE
.PP

.SS "Shopify\&.Unity\&.CustomerActivateInput\&.CustomerActivateInput (Dictionary< string, object > dataJSON)"

.PP
\fBParameters\fP
.RS 4
\fIactivationToken\fP The activation token required to activate the customer\&. 
.br
\fIpassword\fP New password that will be set during activation\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
