.TH "Shopify.Unity.SDK.ConnectionQueryInfo" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.SDK.ConnectionQueryInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConnectionQueryInfo\fP (GetConnectionFromResponseDelegate getConnection, BuildQueryOnEdgesNodeDelegate query, string after=null)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBAfter\fP"
.br
.ti -1c
.RI "GetConnectionFromResponseDelegate \fBGetConnection\fP"
.br
.ti -1c
.RI "BuildQueryOnEdgesNodeDelegate \fBQuery\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
