.TH "Shopify.Unity.SelectedOptionInput" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.SelectedOptionInput \- Specifies the input fields required for a selected option\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShopify\&.Unity\&.SDK\&.InputBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSelectedOptionInput\fP (string \fBname\fP, string \fBvalue\fP)"
.br
.ti -1c
.RI "\fBSelectedOptionInput\fP (Dictionary< string, object > dataJSON)"
.br
.in -1c

Public Member Functions inherited from \fBShopify\&.Unity\&.SDK\&.InputBase\fP
.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns a string representing a GraphQL input object\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBnameFieldKey\fP = 'name'"
.br
.ti -1c
.RI "const string \fBvalueFieldKey\fP = 'value'"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBname\fP\fC [get, set]\fP"
.br
.RI "The product option’s name\&. "
.ti -1c
.RI "string \fBvalue\fP\fC [get, set]\fP"
.br
.RI "The product option’s value\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBShopify\&.Unity\&.SDK\&.InputBase\fP
.in +1c
.ti -1c
.RI "void \fBSet\fP (string key, object value)"
.br
.ti -1c
.RI "object \fBGet\fP (string key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Specifies the input fields required for a selected option\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Shopify\&.Unity\&.SelectedOptionInput\&.SelectedOptionInput (string name, string value)"

.PP
\fBParameters\fP
.RS 4
\fIname\fP The product option’s name\&. 
.br
\fIvalue\fP The product option’s value\&. 
.RE
.PP

.SS "Shopify\&.Unity\&.SelectedOptionInput\&.SelectedOptionInput (Dictionary< string, object > dataJSON)"

.PP
\fBParameters\fP
.RS 4
\fIname\fP The product option’s name\&. 
.br
\fIvalue\fP The product option’s value\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
