.TH "Shopify.Unity.SDK.DefaultProductQueries" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.SDK.DefaultProductQueries \- Generates default queries for ShopifyClient\&.products 
.PP
\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShopProducts\fP (\fBQueryRootQuery\fP query, Dictionary< string, int > imageResolutions, int first=20, string after=null)"
.br
.ti -1c
.RI "void \fBProduct\fP (\fBProductQuery\fP product, Dictionary< string, int > imageResolutions)"
.br
.ti -1c
.RI "void \fBImageConnection\fP (\fBImageConnectionQuery\fP imageConnection, Dictionary< string, int > imageResolutions)"
.br
.ti -1c
.RI "void \fBAliasedTransformedSrcImages\fP (\fBImageQuery\fP imageQuery, Dictionary< string, int > imageResolutions)"
.br
.ti -1c
.RI "void \fBProductVariantConnection\fP (\fBProductVariantConnectionQuery\fP variantConnection, Dictionary< string, int > imageResolutions)"
.br
.ti -1c
.RI "void \fBCollectionConnection\fP (\fBCollectionConnectionQuery\fP collectionConnection)"
.br
.ti -1c
.RI "void \fBImage\fP (\fBImageQuery\fP image)"
.br
.ti -1c
.RI "void \fBProductVariant\fP (\fBProductVariantQuery\fP variant, Dictionary< string, int > imageResolutions)"
.br
.ti -1c
.RI "void \fBCollection\fP (\fBCollectionQuery\fP collection)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generates default queries for ShopifyClient\&.products 
.PP
\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
