.TH "Shopify.Examples.Panels.ProductPanel" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Examples.Panels.ProductPanel
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetCurrentProduct\fP (\fBShopify\&.Unity\&.Product\fP product)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAddProductToCartEvent\fP \fBOnAddProductToCart\fP = new \fBAddProductToCartEvent\fP()"
.br
.ti -1c
.RI "UnityEvent \fBOnReturnToProducts\fP"
.br
.ti -1c
.RI "UnityEvent \fBOnViewCart\fP"
.br
.ti -1c
.RI "Button \fBBackButton\fP"
.br
.ti -1c
.RI "Text \fBProductTitle\fP"
.br
.ti -1c
.RI "Image \fBProductImage\fP"
.br
.ti -1c
.RI "Text \fBProductTitleDescription\fP"
.br
.ti -1c
.RI "Text \fBProductTitleDescNoVariant\fP"
.br
.ti -1c
.RI "Text \fBProductCurrency\fP"
.br
.ti -1c
.RI "Text \fBProductPrice\fP"
.br
.ti -1c
.RI "Button \fBAddToCartButton\fP"
.br
.ti -1c
.RI "Dropdown \fBVariantsDropdown\fP"
.br
.ti -1c
.RI "\fBShopify\&.Unity\&.Product\fP \fBCurrentProduct\fP"
.br
.ti -1c
.RI "\fBShopify\&.Unity\&.ProductVariant\fP \fBCurrentVariant\fP"
.br
.ti -1c
.RI "GameObject \fBthumbnailHolder\fP"
.br
.ti -1c
.RI "\fBImageHolder\fP \fBImageHolderTemplate\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
