.TH "Shopify.Unity.ShopMetadata" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.ShopMetadata \- Data struct containing metadata associated with a Shop\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShopMetadata\fP (string name, \fBPaymentSettings\fP paymentSettings)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly string \fBName\fP"
.br
.ti -1c
.RI "readonly \fBPaymentSettings\fP \fBPaymentSettings\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data struct containing metadata associated with a Shop\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
