.TH "Shopify.Unity.SDK.ConnectionLoader" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.SDK.ConnectionLoader
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConnectionLoader\fP (\fBQueryLoader\fP loader)"
.br
.ti -1c
.RI "void \fBQueryConnection\fP (BuildQueryOnConnectionLoopDelegate getQuery, GetConnectionFromResponseDelegate getConnection, QueryResponseHandler callback)"
.br
.ti -1c
.RI "void \fBQueryConnectionsOnNodes\fP (List< \fBNode\fP > nodes, List< \fBConnectionQueryInfo\fP > connectionInfos, BuildQueryOnNodeDelegate buildQuery, ResponseNodeHandler callback)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
