.TH "Shopify.Unity.VersionInformation" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.VersionInformation
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBVERSION\fP = '2\&.1\&.1\-github'"
.br
.RI "Version of the \fBShopify\fP SDK for Unity\&. "
.ti -1c
.RI "const string \fBPUBLISH_DESTINATION\fP = 'github'"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const string Shopify\&.Unity\&.VersionInformation\&.VERSION = '2\&.1\&.1\-github'\fC [static]\fP"

.PP
Version of the \fBShopify\fP SDK for Unity\&. 
.PP
.nf
// Example that checks the SDK version
Debug\&.Log("Current SDK Version: " + ShopifyBuy\&.VERSION);

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
