.TH "Shopify.Unity.GraphQL.MetafieldQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.MetafieldQuery \- Metafields represent custom metadata attached to a resource\&. Metafields can be sorted into namespaces and are comprised of keys, values, and value types\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMetafieldQuery\fP (StringBuilder query)"
.br
.RI "MetafieldQuery is used to build queries\&. Typically MetafieldQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBMetafieldQuery\fP \fBdescription\fP ()"
.br
.RI "The description of a metafield\&. "
.ti -1c
.RI "\fBMetafieldQuery\fP \fBid\fP ()"
.br
.RI "Globally unique identifier\&. "
.ti -1c
.RI "\fBMetafieldQuery\fP \fBkey\fP ()"
.br
.RI "The key name for a metafield\&. "
.ti -1c
.RI "\fBMetafieldQuery\fP \fBnamespaceValue\fP ()"
.br
.RI "The namespace for a metafield\&. "
.ti -1c
.RI "\fBMetafieldQuery\fP \fBparentResource\fP (MetafieldParentResourceDelegate buildQuery)"
.br
.RI "The parent object that the metafield belongs to\&. "
.ti -1c
.RI "\fBMetafieldQuery\fP \fBvalue\fP ()"
.br
.RI "The value of a metafield\&. "
.ti -1c
.RI "\fBMetafieldQuery\fP \fBvalueType\fP ()"
.br
.RI "Represents the metafield value type\&. "
.in -1c
.SH "Detailed Description"
.PP 
Metafields represent custom metadata attached to a resource\&. Metafields can be sorted into namespaces and are comprised of keys, values, and value types\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
