.TH "Shopify.Examples.Panels.ShowProductEvent" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Examples.Panels.ShowProductEvent
.SH SYNOPSIS
.br
.PP
.PP
Inherits UnityEvent< Shopify\&.Unity\&.Product >\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
