.TH "Shopify.Unity.GraphQL.CustomerCreatePayloadQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.CustomerCreatePayloadQuery \- Return type for \fCcustomerCreate\fP mutation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCustomerCreatePayloadQuery\fP (StringBuilder query)"
.br
.RI "CustomerCreatePayloadQuery is used to build queries\&. Typically CustomerCreatePayloadQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBCustomerCreatePayloadQuery\fP \fBcustomer\fP (CustomerDelegate buildQuery)"
.br
.RI "The created customer object\&. "
.ti -1c
.RI "\fBCustomerCreatePayloadQuery\fP \fBcustomerUserErrors\fP (CustomerUserErrorDelegate buildQuery)"
.br
.RI "List of errors that occurred executing the mutation\&. "
.ti -1c
.RI "\fBCustomerCreatePayloadQuery\fP \fBuserErrors\fP (UserErrorDelegate buildQuery)"
.br
.RI "List of errors that occurred executing the mutation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Return type for \fCcustomerCreate\fP mutation\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBCustomerCreatePayloadQuery\fP Shopify\&.Unity\&.GraphQL\&.CustomerCreatePayloadQuery\&.userErrors (UserErrorDelegate buildQuery)"

.PP
List of errors that occurred executing the mutation\&. 
.PP
\fBDeprecated\fP
.RS 4
Use \fCcustomerUserErrors\fP instead 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
