.TH "Shopify.Unity.SDK.SummaryItem" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.SDK.SummaryItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShopify\&.Unity\&.SDK\&.Serializable\fP\&.
.PP
Inherited by \fBShopify\&.Unity\&.SDK\&.ShippingMethod\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSummaryItem\fP (string label, string amount)"
.br
.ti -1c
.RI "override object \fBToJson\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBShopify\&.Unity\&.SDK\&.Serializable\fP
.in +1c
.ti -1c
.RI "string \fBToJsonString\fP ()"
.br
.ti -1c
.RI "object \fBToJson\fP ()"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBLabel\fP"
.br
.ti -1c
.RI "string \fBAmount\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "const string \fBLABEL\fP = 'Label'"
.br
.ti -1c
.RI "const string \fBAMOUNT\fP = 'Amount'"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
