.TH "Shopify.Unity.DiscountApplication" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.DiscountApplication \- Discount applications capture the intentions of a discount source at the time of application\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBShopify\&.Unity\&.AutomaticDiscountApplication\fP, \fBShopify\&.Unity\&.DiscountCodeApplication\fP, \fBShopify\&.Unity\&.ManualDiscountApplication\fP, \fBShopify\&.Unity\&.ScriptDiscountApplication\fP, and \fBShopify\&.Unity\&.UnknownDiscountApplication\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDiscountApplicationAllocationMethod\fP \fBallocationMethod\fP ()"
.br
.RI "The method by which the discount's value is allocated to its entitled items\&. "
.ti -1c
.RI "\fBDiscountApplicationTargetSelection\fP \fBtargetSelection\fP ()"
.br
.RI "Which lines of targetType that the discount is allocated over\&. "
.ti -1c
.RI "\fBDiscountApplicationTargetType\fP \fBtargetType\fP ()"
.br
.RI "The type of line that the discount is applicable towards\&. "
.ti -1c
.RI "\fBPricingValue\fP \fBvalue\fP ()"
.br
.RI "The value of the discount application\&. "
.in -1c
.SH "Detailed Description"
.PP 
Discount applications capture the intentions of a discount source at the time of application\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBDiscountApplicationAllocationMethod\fP Shopify\&.Unity\&.DiscountApplication\&.allocationMethod ()"

.PP
The method by which the discount's value is allocated to its entitled items\&. 
.PP
Implemented in \fBShopify\&.Unity\&.AutomaticDiscountApplication\fP, \fBShopify\&.Unity\&.UnknownDiscountApplication\fP, \fBShopify\&.Unity\&.DiscountCodeApplication\fP, \fBShopify\&.Unity\&.ManualDiscountApplication\fP, and \fBShopify\&.Unity\&.ScriptDiscountApplication\fP\&.
.SS "\fBDiscountApplicationTargetSelection\fP Shopify\&.Unity\&.DiscountApplication\&.targetSelection ()"

.PP
Which lines of targetType that the discount is allocated over\&. 
.PP
Implemented in \fBShopify\&.Unity\&.AutomaticDiscountApplication\fP, \fBShopify\&.Unity\&.UnknownDiscountApplication\fP, \fBShopify\&.Unity\&.DiscountCodeApplication\fP, \fBShopify\&.Unity\&.ManualDiscountApplication\fP, and \fBShopify\&.Unity\&.ScriptDiscountApplication\fP\&.
.SS "\fBDiscountApplicationTargetType\fP Shopify\&.Unity\&.DiscountApplication\&.targetType ()"

.PP
The type of line that the discount is applicable towards\&. 
.PP
Implemented in \fBShopify\&.Unity\&.AutomaticDiscountApplication\fP, \fBShopify\&.Unity\&.UnknownDiscountApplication\fP, \fBShopify\&.Unity\&.DiscountCodeApplication\fP, \fBShopify\&.Unity\&.ManualDiscountApplication\fP, and \fBShopify\&.Unity\&.ScriptDiscountApplication\fP\&.
.SS "\fBPricingValue\fP Shopify\&.Unity\&.DiscountApplication\&.value ()"

.PP
The value of the discount application\&. 
.PP
Implemented in \fBShopify\&.Unity\&.AutomaticDiscountApplication\fP, \fBShopify\&.Unity\&.UnknownDiscountApplication\fP, \fBShopify\&.Unity\&.DiscountCodeApplication\fP, \fBShopify\&.Unity\&.ManualDiscountApplication\fP, and \fBShopify\&.Unity\&.ScriptDiscountApplication\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
