.TH "Shopify.Unity.MoneyInput" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.MoneyInput \- Specifies the fields for a monetary value with currency\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShopify\&.Unity\&.SDK\&.InputBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMoneyInput\fP (decimal \fBamount\fP, \fBCurrencyCode\fP \fBcurrencyCode\fP)"
.br
.ti -1c
.RI "\fBMoneyInput\fP (Dictionary< string, object > dataJSON)"
.br
.in -1c

Public Member Functions inherited from \fBShopify\&.Unity\&.SDK\&.InputBase\fP
.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns a string representing a GraphQL input object\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBamountFieldKey\fP = 'amount'"
.br
.ti -1c
.RI "const string \fBcurrencyCodeFieldKey\fP = 'currencyCode'"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "decimal \fBamount\fP\fC [get, set]\fP"
.br
.RI "Decimal money amount\&. "
.ti -1c
.RI "\fBCurrencyCode\fP \fBcurrencyCode\fP\fC [get, set]\fP"
.br
.RI "Currency of the money\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBShopify\&.Unity\&.SDK\&.InputBase\fP
.in +1c
.ti -1c
.RI "void \fBSet\fP (string key, object value)"
.br
.ti -1c
.RI "object \fBGet\fP (string key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Specifies the fields for a monetary value with currency\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Shopify\&.Unity\&.MoneyInput\&.MoneyInput (decimal amount, \fBCurrencyCode\fP currencyCode)"

.PP
\fBParameters\fP
.RS 4
\fIamount\fP Decimal money amount\&. 
.br
\fIcurrencyCode\fP Currency of the money\&. 
.RE
.PP

.SS "Shopify\&.Unity\&.MoneyInput\&.MoneyInput (Dictionary< string, object > dataJSON)"

.PP
\fBParameters\fP
.RS 4
\fIamount\fP Decimal money amount\&. 
.br
\fIcurrencyCode\fP Currency of the money\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
