.TH "Shopify.Unity.DisplayableError" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.DisplayableError \- Represents an error in the input of a mutation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBShopify\&.Unity\&.CheckoutUserError\fP, \fBShopify\&.Unity\&.CustomerUserError\fP, \fBShopify\&.Unity\&.UnknownDisplayableError\fP, and \fBShopify\&.Unity\&.UserError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "List< string > \fBfield\fP ()"
.br
.RI "Path to the input field which caused the error\&. "
.ti -1c
.RI "string \fBmessage\fP ()"
.br
.RI "The error message\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents an error in the input of a mutation\&. 
.SH "Member Function Documentation"
.PP 
.SS "List< string > Shopify\&.Unity\&.DisplayableError\&.field ()"

.PP
Path to the input field which caused the error\&. 
.PP
Implemented in \fBShopify\&.Unity\&.CheckoutUserError\fP, \fBShopify\&.Unity\&.CustomerUserError\fP, \fBShopify\&.Unity\&.UnknownDisplayableError\fP, and \fBShopify\&.Unity\&.UserError\fP\&.
.SS "string Shopify\&.Unity\&.DisplayableError\&.message ()"

.PP
The error message\&. 
.PP
Implemented in \fBShopify\&.Unity\&.CheckoutUserError\fP, \fBShopify\&.Unity\&.CustomerUserError\fP, \fBShopify\&.Unity\&.UnknownDisplayableError\fP, and \fBShopify\&.Unity\&.UserError\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
