.TH "Shopify.Examples.LineItems" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Examples.LineItems
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCartPanelLineItem\fP"
.br
.ti -1c
.RI "class \fBVariantLineItemQuantityAdjustmentEvent\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
