.TH "Shopify.Unity.NoMatchingVariantException" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.NoMatchingVariantException \- This exception is thrown when interacting with a cart to add, update, or delete line items and no matching variant could be found\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNoMatchingVariantException\fP (string message)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This exception is thrown when interacting with a cart to add, update, or delete line items and no matching variant could be found\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
