.TH "Shopify.Unity.GraphQL.PricingValueQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.PricingValueQuery \- The price value (fixed or percentage) for a discount application\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPricingValueQuery\fP (StringBuilder query)"
.br
.RI "PricingValueQuery is used to build queries\&. Typically PricingValueQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBPricingValueQuery\fP \fBonMoneyV2\fP (MoneyV2Delegate buildQuery)"
.br
.RI "will allow you to write queries on MoneyV2\&. "
.ti -1c
.RI "\fBPricingValueQuery\fP \fBonPricingPercentageValue\fP (PricingPercentageValueDelegate buildQuery)"
.br
.RI "will allow you to write queries on PricingPercentageValue\&. "
.in -1c
.SH "Detailed Description"
.PP 
The price value (fixed or percentage) for a discount application\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
