.TH "Shopify.Unity.SDK.NativePayment" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.SDK.NativePayment
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNativePayment\fP (string stringJson)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly \fBMailingAddressInput\fP \fBBillingAddress\fP"
.br
.ti -1c
.RI "readonly \fBMailingAddressInput\fP \fBShippingAddress\fP"
.br
.ti -1c
.RI "readonly string \fBEmail\fP"
.br
.ti -1c
.RI "readonly string \fBShippingIdentifier\fP"
.br
.ti -1c
.RI "readonly string \fBTransactionIdentifier\fP"
.br
.ti -1c
.RI "readonly string \fBIdentifier\fP"
.br
.ti -1c
.RI "readonly string \fBPaymentData\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
