.TH "Shopify.Unity.GraphQL.FulfillmentLineItemQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.FulfillmentLineItemQuery \- Represents a single line item in a fulfillment\&. There is at most one fulfillment line item for each order line item\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFulfillmentLineItemQuery\fP (StringBuilder query)"
.br
.RI "FulfillmentLineItemQuery is used to build queries\&. Typically FulfillmentLineItemQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBFulfillmentLineItemQuery\fP \fBlineItem\fP (OrderLineItemDelegate buildQuery)"
.br
.RI "The associated order's line item\&. "
.ti -1c
.RI "\fBFulfillmentLineItemQuery\fP \fBquantity\fP ()"
.br
.RI "The amount fulfilled in this fulfillment\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a single line item in a fulfillment\&. There is at most one fulfillment line item for each order line item\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
