.TH "ShopPopup" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShopPopup
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShowPopup\fP ()"
.br
.ti -1c
.RI "void \fBHidePopup\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ProductsPanel \fBProductsPanel\fP"
.br
.ti -1c
.RI "ProductPanel \fBProductPanel\fP"
.br
.ti -1c
.RI "CartPanel \fBCartPanel\fP"
.br
.ti -1c
.RI "EmptyCartPanel \fBEmptyCartPanel\fP"
.br
.ti -1c
.RI "ErrorPanel \fBErrorPanel\fP"
.br
.ti -1c
.RI "ViewCartButton \fBViewCartButton\fP"
.br
.ti -1c
.RI "Button \fBEmptyViewCartButton\fP"
.br
.ti -1c
.RI "\fBAnimationCanvas\fP \fBAnimationCanvas\fP"
.br
.ti -1c
.RI "Animator \fBAnimationCanvasAnimator\fP"
.br
.ti -1c
.RI "Animator \fBErrorPanelAnimator\fP"
.br
.ti -1c
.RI "UnityEvent \fBOnPanelOpen\fP"
.br
.ti -1c
.RI "UnityEvent \fBOnPanelClose\fP"
.br
.ti -1c
.RI "GameObject \fBdimmer\fP"
.br
.ti -1c
.RI "string \fBAccessToken\fP = '8f40b2ede3e02be97a81ac29cfabc6e0'"
.br
.ti -1c
.RI "string \fBShopDomain\fP = 'unity\-buy\-sdk\&.myshopify\&.com'"
.br
.ti -1c
.RI "string \fBLocale\fP"
.br
.ti -1c
.RI "string \fBiOSMerchantID\fP = ''"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
