.TH "Shopify.Examples.Panels.EmptyCartPanel" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Examples.Panels.EmptyCartPanel
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Button \fBBackToProductsButton\fP"
.br
.ti -1c
.RI "Button \fBContinueButton\fP"
.br
.ti -1c
.RI "UnityEvent \fBOnReturnToProducts\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
