.TH "Shopify.Unity.MiniJSON" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.MiniJSON
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJson\fP"
.br
.RI "This class encodes and decodes JSON strings\&. Spec\&. details, see http://www.json.org/\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
