.TH "ShopifySDKExampleStandardAssets.ImageEffects" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShopifySDKExampleStandardAssets.ImageEffects
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBlurOptimized\fP"
.br
.ti -1c
.RI "class \fBPostEffectsBase\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
