.TH "Shopify.Unity.AttributeInput" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.AttributeInput \- Specifies the input fields required for an attribute\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShopify\&.Unity\&.SDK\&.InputBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAttributeInput\fP (string \fBkey\fP, string \fBvalue\fP)"
.br
.ti -1c
.RI "\fBAttributeInput\fP (Dictionary< string, object > dataJSON)"
.br
.in -1c

Public Member Functions inherited from \fBShopify\&.Unity\&.SDK\&.InputBase\fP
.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns a string representing a GraphQL input object\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBkeyFieldKey\fP = 'key'"
.br
.ti -1c
.RI "const string \fBvalueFieldKey\fP = 'value'"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBkey\fP\fC [get, set]\fP"
.br
.RI "Key or name of the attribute\&. "
.ti -1c
.RI "string \fBvalue\fP\fC [get, set]\fP"
.br
.RI "Value of the attribute\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBShopify\&.Unity\&.SDK\&.InputBase\fP
.in +1c
.ti -1c
.RI "void \fBSet\fP (string key, object value)"
.br
.ti -1c
.RI "object \fBGet\fP (string key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Specifies the input fields required for an attribute\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Shopify\&.Unity\&.AttributeInput\&.AttributeInput (string key, string value)"

.PP
\fBParameters\fP
.RS 4
\fIkey\fP Key or name of the attribute\&. 
.br
\fIvalue\fP Value of the attribute\&. 
.RE
.PP

.SS "Shopify\&.Unity\&.AttributeInput\&.AttributeInput (Dictionary< string, object > dataJSON)"

.PP
\fBParameters\fP
.RS 4
\fIkey\fP Key or name of the attribute\&. 
.br
\fIvalue\fP Value of the attribute\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
