.TH "Shopify.Unity.GraphQL.PageInfoQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.PageInfoQuery \- Information about pagination in a connection\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPageInfoQuery\fP (StringBuilder query)"
.br
.RI "PageInfoQuery is used to build queries\&. Typically PageInfoQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBPageInfoQuery\fP \fBhasNextPage\fP ()"
.br
.RI "Indicates if there are more pages to fetch\&. "
.ti -1c
.RI "\fBPageInfoQuery\fP \fBhasPreviousPage\fP ()"
.br
.RI "Indicates if there are any pages prior to the current page\&. "
.in -1c
.SH "Detailed Description"
.PP 
Information about pagination in a connection\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
