.TH "Shopify.Unity.Media" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.Media \- Represents a media interface\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBShopify\&.Unity\&.ExternalVideo\fP, \fBShopify\&.Unity\&.MediaImage\fP, \fBShopify\&.Unity\&.Model3d\fP, \fBShopify\&.Unity\&.UnknownMedia\fP, and \fBShopify\&.Unity\&.Video\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBalt\fP ()"
.br
.RI "A word or phrase to share the nature or contents of a media\&. "
.ti -1c
.RI "\fBMediaContentType\fP \fBmediaContentType\fP ()"
.br
.RI "The media content type\&. "
.ti -1c
.RI "\fBImage\fP \fBpreviewImage\fP ()"
.br
.RI "The preview image for the media\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a media interface\&. 
.SH "Member Function Documentation"
.PP 
.SS "string Shopify\&.Unity\&.Media\&.alt ()"

.PP
A word or phrase to share the nature or contents of a media\&. 
.PP
Implemented in \fBShopify\&.Unity\&.ExternalVideo\fP, \fBShopify\&.Unity\&.UnknownMedia\fP, \fBShopify\&.Unity\&.MediaImage\fP, \fBShopify\&.Unity\&.Model3d\fP, and \fBShopify\&.Unity\&.Video\fP\&.
.SS "\fBMediaContentType\fP Shopify\&.Unity\&.Media\&.mediaContentType ()"

.PP
The media content type\&. 
.PP
Implemented in \fBShopify\&.Unity\&.ExternalVideo\fP, \fBShopify\&.Unity\&.UnknownMedia\fP, \fBShopify\&.Unity\&.MediaImage\fP, \fBShopify\&.Unity\&.Model3d\fP, and \fBShopify\&.Unity\&.Video\fP\&.
.SS "\fBImage\fP Shopify\&.Unity\&.Media\&.previewImage ()"

.PP
The preview image for the media\&. 
.PP
Implemented in \fBShopify\&.Unity\&.ExternalVideo\fP, \fBShopify\&.Unity\&.UnknownMedia\fP, \fBShopify\&.Unity\&.MediaImage\fP, \fBShopify\&.Unity\&.Model3d\fP, and \fBShopify\&.Unity\&.Video\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
