.TH "Shopify.Examples.LineItems.CartPanelLineItem" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Examples.LineItems.CartPanelLineItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetCurrentProduct\fP (\fBProduct\fP product, \fBProductVariant\fP variant, int quantity)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVariantLineItemQuantityAdjustmentEvent\fP \fBOnVariantLineItemQuantityAdjustment\fP = new \fBVariantLineItemQuantityAdjustmentEvent\fP()"
.br
.ti -1c
.RI "Text \fBProductTitle\fP"
.br
.ti -1c
.RI "Text \fBVariantTitle\fP"
.br
.ti -1c
.RI "Text \fBQuantity\fP"
.br
.ti -1c
.RI "Text \fBPrice\fP"
.br
.ti -1c
.RI "\fBImage\fP \fBProductImage\fP"
.br
.ti -1c
.RI "Button \fBIncreaseQuantity\fP"
.br
.ti -1c
.RI "Button \fBDecreaseQuantity\fP"
.br
.ti -1c
.RI "\fBImage\fP \fBSeparatorLine\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
