.TH "Shopify.Unity.GraphQL.AttributeQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.AttributeQuery \- Represents a generic custom attribute\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAttributeQuery\fP (StringBuilder query)"
.br
.RI "AttributeQuery is used to build queries\&. Typically AttributeQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBAttributeQuery\fP \fBkey\fP ()"
.br
.RI "Key or name of the attribute\&. "
.ti -1c
.RI "\fBAttributeQuery\fP \fBvalue\fP ()"
.br
.RI "Value of the attribute\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a generic custom attribute\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
