.TH "Shopify.Unity.HasMetafields" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.HasMetafields \- Represents information about the metafields associated to the specified resource\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBShopify\&.Unity\&.Product\fP, \fBShopify\&.Unity\&.ProductVariant\fP, and \fBShopify\&.Unity\&.UnknownHasMetafields\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMetafield\fP \fBmetafield\fP (string alias=null)"
.br
.RI "The metafield associated with the resource\&. "
.ti -1c
.RI "\fBMetafieldConnection\fP \fBmetafields\fP (string alias=null)"
.br
.RI "A paginated list of metafields associated with the resource\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents information about the metafields associated to the specified resource\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBMetafield\fP Shopify\&.Unity\&.HasMetafields\&.metafield (string alias = \fCnull\fP)"

.PP
The metafield associated with the resource\&. 
.PP
\fBParameters\fP
.RS 4
\fIalias\fP If the original field queried was queried using an alias, then pass the matching string\&. 
.RE
.PP

.PP
Implemented in \fBShopify\&.Unity\&.UnknownHasMetafields\fP, \fBShopify\&.Unity\&.Product\fP, and \fBShopify\&.Unity\&.ProductVariant\fP\&.
.SS "\fBMetafieldConnection\fP Shopify\&.Unity\&.HasMetafields\&.metafields (string alias = \fCnull\fP)"

.PP
A paginated list of metafields associated with the resource\&. 
.PP
\fBParameters\fP
.RS 4
\fIalias\fP If the original field queried was queried using an alias, then pass the matching string\&. 
.RE
.PP

.PP
Implemented in \fBShopify\&.Unity\&.UnknownHasMetafields\fP, \fBShopify\&.Unity\&.Product\fP, and \fBShopify\&.Unity\&.ProductVariant\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
