.TH "Shopify.Examples.Panels.ProductsPanelCell" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Examples.Panels.ProductsPanelCell
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLoad\fP ()"
.br
.ti -1c
.RI "void \fBSetCurrentProduct\fP (\fBShopify\&.Unity\&.Product\fP product, int index)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UnityEvent \fBOnClick\fP"
.br
.ti -1c
.RI "int \fBMaxDescriptionCharacters\fP = 150"
.br
.ti -1c
.RI "Text \fBTitleText\fP"
.br
.ti -1c
.RI "Text \fBDescriptionText\fP"
.br
.ti -1c
.RI "Image \fBProductImage\fP"
.br
.ti -1c
.RI "Text \fBCurrencyText\fP"
.br
.ti -1c
.RI "Text \fBPriceText\fP"
.br
.ti -1c
.RI "Button \fBClickRegionButton\fP"
.br
.ti -1c
.RI "Image \fBSeparatorLine\fP"
.br
.ti -1c
.RI "Image \fBBrokenImageIcon\fP"
.br
.ti -1c
.RI "RectTransform \fBRectTransform\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsLoaded\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
