.TH "Shopify.Unity.GraphQL.CustomerResetByUrlPayloadQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.CustomerResetByUrlPayloadQuery \- Return type for \fCcustomerResetByUrl\fP mutation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCustomerResetByUrlPayloadQuery\fP (StringBuilder query)"
.br
.RI "CustomerResetByUrlPayloadQuery is used to build queries\&. Typically CustomerResetByUrlPayloadQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBCustomerResetByUrlPayloadQuery\fP \fBcustomer\fP (CustomerDelegate buildQuery)"
.br
.RI "The customer object which was reset\&. "
.ti -1c
.RI "\fBCustomerResetByUrlPayloadQuery\fP \fBcustomerAccessToken\fP (CustomerAccessTokenDelegate buildQuery)"
.br
.RI "A newly created customer access token object for the customer\&. "
.ti -1c
.RI "\fBCustomerResetByUrlPayloadQuery\fP \fBcustomerUserErrors\fP (CustomerUserErrorDelegate buildQuery)"
.br
.RI "List of errors that occurred executing the mutation\&. "
.ti -1c
.RI "\fBCustomerResetByUrlPayloadQuery\fP \fBuserErrors\fP (UserErrorDelegate buildQuery)"
.br
.RI "List of errors that occurred executing the mutation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Return type for \fCcustomerResetByUrl\fP mutation\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBCustomerResetByUrlPayloadQuery\fP Shopify\&.Unity\&.GraphQL\&.CustomerResetByUrlPayloadQuery\&.userErrors (UserErrorDelegate buildQuery)"

.PP
List of errors that occurred executing the mutation\&. 
.PP
\fBDeprecated\fP
.RS 4
Use \fCcustomerUserErrors\fP instead 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
