.TH "Shopify.Unity.GraphQL.ExternalVideoQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.ExternalVideoQuery \- Represents a video hosted outside of \fBShopify\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExternalVideoQuery\fP (StringBuilder query)"
.br
.RI "ExternalVideoQuery is used to build queries\&. Typically ExternalVideoQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBExternalVideoQuery\fP \fBalt\fP ()"
.br
.RI "A word or phrase to share the nature or contents of a media\&. "
.ti -1c
.RI "\fBExternalVideoQuery\fP \fBembeddedUrl\fP ()"
.br
.RI "The URL\&. "
.ti -1c
.RI "\fBExternalVideoQuery\fP \fBid\fP ()"
.br
.RI "Globally unique identifier\&. "
.ti -1c
.RI "\fBExternalVideoQuery\fP \fBmediaContentType\fP ()"
.br
.RI "The media content type\&. "
.ti -1c
.RI "\fBExternalVideoQuery\fP \fBpreviewImage\fP (ImageDelegate buildQuery)"
.br
.RI "The preview image for the media\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a video hosted outside of \fBShopify\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
