.TH "Shopify.Unity.GraphQL.CustomerAddressCreatePayloadQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.CustomerAddressCreatePayloadQuery \- Return type for \fCcustomerAddressCreate\fP mutation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCustomerAddressCreatePayloadQuery\fP (StringBuilder query)"
.br
.RI "CustomerAddressCreatePayloadQuery is used to build queries\&. Typically CustomerAddressCreatePayloadQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBCustomerAddressCreatePayloadQuery\fP \fBcustomerAddress\fP (MailingAddressDelegate buildQuery)"
.br
.RI "The new customer address object\&. "
.ti -1c
.RI "\fBCustomerAddressCreatePayloadQuery\fP \fBcustomerUserErrors\fP (CustomerUserErrorDelegate buildQuery)"
.br
.RI "List of errors that occurred executing the mutation\&. "
.ti -1c
.RI "\fBCustomerAddressCreatePayloadQuery\fP \fBuserErrors\fP (UserErrorDelegate buildQuery)"
.br
.RI "List of errors that occurred executing the mutation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Return type for \fCcustomerAddressCreate\fP mutation\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBCustomerAddressCreatePayloadQuery\fP Shopify\&.Unity\&.GraphQL\&.CustomerAddressCreatePayloadQuery\&.userErrors (UserErrorDelegate buildQuery)"

.PP
List of errors that occurred executing the mutation\&. 
.PP
\fBDeprecated\fP
.RS 4
Use \fCcustomerUserErrors\fP instead 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
