.TH "Shopify.Unity.UI.NativePayButtonUI" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.UI.NativePayButtonUI
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBOnRectTransformDimensionsChange\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
