.TH "Shopify.Unity.GraphQL.UserErrorQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.UserErrorQuery \- Represents an error in the input of a mutation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUserErrorQuery\fP (StringBuilder query)"
.br
.RI "UserErrorQuery is used to build queries\&. Typically UserErrorQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBUserErrorQuery\fP \fBfield\fP ()"
.br
.RI "Path to the input field which caused the error\&. "
.ti -1c
.RI "\fBUserErrorQuery\fP \fBmessage\fP ()"
.br
.RI "The error message\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents an error in the input of a mutation\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
