.TH "Shopify.Unity.GraphQL.DomainQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.DomainQuery \- Represents a web address\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDomainQuery\fP (StringBuilder query)"
.br
.RI "DomainQuery is used to build queries\&. Typically DomainQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBDomainQuery\fP \fBhost\fP ()"
.br
.RI "The host name of the domain (eg: \fCexample\&.com\fP)\&. "
.ti -1c
.RI "\fBDomainQuery\fP \fBsslEnabled\fP ()"
.br
.RI "Whether SSL is enabled or not\&. "
.ti -1c
.RI "\fBDomainQuery\fP \fBurl\fP ()"
.br
.RI "The URL of the domain (eg: \fChttps://example.com\fP)\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a web address\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
