.TH "Shopify.Unity.SDK.Arguments" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.SDK.Arguments \- Is used by GraphQL generator classes to create argument strings\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAdd\fP (string name, object value)"
.br
.RI "Adds an argument\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns a string that is the a GraphQL argument list\&. "
.in -1c
.SH "Detailed Description"
.PP 
Is used by GraphQL generator classes to create argument strings\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Shopify\&.Unity\&.SDK\&.Arguments\&.Add (string name, object value)"

.PP
Adds an argument\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP Name of the argument to be added
.br
\fIvalue\fP Value of the argument to be added
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
