.TH "Shopify.Unity.GraphQL.ShopPolicyQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.ShopPolicyQuery \- Policy that a merchant has configured for their store, such as their refund or privacy policy\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShopPolicyQuery\fP (StringBuilder query)"
.br
.RI "ShopPolicyQuery is used to build queries\&. Typically ShopPolicyQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBShopPolicyQuery\fP \fBbody\fP ()"
.br
.RI "Policy text, maximum size of 64kb\&. "
.ti -1c
.RI "\fBShopPolicyQuery\fP \fBhandle\fP ()"
.br
.RI "Policy’s handle\&. "
.ti -1c
.RI "\fBShopPolicyQuery\fP \fBid\fP ()"
.br
.RI "Globally unique identifier\&. "
.ti -1c
.RI "\fBShopPolicyQuery\fP \fBtitle\fP ()"
.br
.RI "Policy’s title\&. "
.ti -1c
.RI "\fBShopPolicyQuery\fP \fBurl\fP ()"
.br
.RI "Public URL to the policy\&. "
.in -1c
.SH "Detailed Description"
.PP 
Policy that a merchant has configured for their store, such as their refund or privacy policy\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
