.TH "Shopify.Unity.GraphQL.CustomerAccessTokenRenewPayloadQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.CustomerAccessTokenRenewPayloadQuery \- Return type for \fCcustomerAccessTokenRenew\fP mutation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCustomerAccessTokenRenewPayloadQuery\fP (StringBuilder query)"
.br
.RI "CustomerAccessTokenRenewPayloadQuery is used to build queries\&. Typically CustomerAccessTokenRenewPayloadQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBCustomerAccessTokenRenewPayloadQuery\fP \fBcustomerAccessToken\fP (CustomerAccessTokenDelegate buildQuery)"
.br
.RI "The renewed customer access token object\&. "
.ti -1c
.RI "\fBCustomerAccessTokenRenewPayloadQuery\fP \fBuserErrors\fP (UserErrorDelegate buildQuery)"
.br
.RI "List of errors that occurred executing the mutation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Return type for \fCcustomerAccessTokenRenew\fP mutation\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
