.TH "Shopify.Unity.ExternalVideo" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.ExternalVideo \- Represents a video hosted outside of \fBShopify\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShopify\&.Unity\&.SDK\&.AbstractResponse\fP, ICloneable, \fBShopify\&.Unity\&.Media\fP, and \fBShopify\&.Unity\&.Node\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExternalVideo\fP (Dictionary< string, object > dataJSON)"
.br
.RI "Accepts deserialized json data\&.  Will further parse passed in data\&. "
.ti -1c
.RI "string \fBalt\fP ()"
.br
.RI "A word or phrase to share the nature or contents of a media\&. "
.ti -1c
.RI "string \fBembeddedUrl\fP ()"
.br
.RI "The URL\&. "
.ti -1c
.RI "string \fBid\fP ()"
.br
.RI "Globally unique identifier\&. "
.ti -1c
.RI "\fBMediaContentType\fP \fBmediaContentType\fP ()"
.br
.RI "The media content type\&. "
.ti -1c
.RI "\fBImage\fP \fBpreviewImage\fP ()"
.br
.RI "The preview image for the media\&. "
.ti -1c
.RI "object \fBClone\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBShopify\&.Unity\&.SDK\&.AbstractResponse\fP
.in +1c
.ti -1c
.RI "T \fBGet< T >\fP (string field, string alias=null)"
.br
.in -1c

Protected Attributes inherited from \fBShopify\&.Unity\&.SDK\&.AbstractResponse\fP
.in +1c
.ti -1c
.RI "Dictionary< string, object > \fBData\fP"
.br
.in -1c

Properties inherited from \fBShopify\&.Unity\&.SDK\&.AbstractResponse\fP
.in +1c
.ti -1c
.RI "Dictionary< string, object > \fBDataJSON\fP\fC [get, protected set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a video hosted outside of \fBShopify\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Shopify\&.Unity\&.ExternalVideo\&.ExternalVideo (Dictionary< string, object > dataJSON)"

.PP
Accepts deserialized json data\&.  Will further parse passed in data\&. 
.PP
\fBParameters\fP
.RS 4
\fIdataJSON\fP Deserialized JSON data for ExternalVideo
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "string Shopify\&.Unity\&.ExternalVideo\&.alt ()"

.PP
A word or phrase to share the nature or contents of a media\&. 
.PP
Implements \fBShopify\&.Unity\&.Media\fP\&.
.SS "string Shopify\&.Unity\&.ExternalVideo\&.id ()"

.PP
Globally unique identifier\&. 
.PP
Implements \fBShopify\&.Unity\&.Node\fP\&.
.SS "\fBMediaContentType\fP Shopify\&.Unity\&.ExternalVideo\&.mediaContentType ()"

.PP
The media content type\&. 
.PP
Implements \fBShopify\&.Unity\&.Media\fP\&.
.SS "\fBImage\fP Shopify\&.Unity\&.ExternalVideo\&.previewImage ()"

.PP
The preview image for the media\&. 
.PP
Implements \fBShopify\&.Unity\&.Media\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
