.TH "Shopify.Unity.SDK.GlobalGameObject" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.SDK.GlobalGameObject
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBDestroy\fP ()"
.br
.ti -1c
.RI "static T \fBAddComponent< T >\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static string \fBName\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static T Shopify\&.Unity\&.SDK\&.GlobalGameObject\&.AddComponent< T > ()\fC [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIComponent\fP


.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
