.TH "Shopify.Unity.GraphQL.CustomerAccessTokenQuery" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shopify.Unity.GraphQL.CustomerAccessTokenQuery \- A CustomerAccessToken represents the unique token required to make modifications to the customer object\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCustomerAccessTokenQuery\fP (StringBuilder query)"
.br
.RI "CustomerAccessTokenQuery is used to build queries\&. Typically CustomerAccessTokenQuery will not be used directly but instead will be used when building queries from either QueryRootQuery or MutationQuery\&. "
.ti -1c
.RI "\fBCustomerAccessTokenQuery\fP \fBaccessToken\fP ()"
.br
.RI "The customer’s access token\&. "
.ti -1c
.RI "\fBCustomerAccessTokenQuery\fP \fBexpiresAt\fP ()"
.br
.RI "The date and time when the customer access token expires\&. "
.in -1c
.SH "Detailed Description"
.PP 
A CustomerAccessToken represents the unique token required to make modifications to the customer object\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
