.TH "TMPro.Examples.CameraController" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples.CameraController
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBCameraModes\fP { \fBFollow\fP, \fBIsometric\fP, \fBFree\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBCameraTarget\fP"
.br
.ti -1c
.RI "float \fBFollowDistance\fP = 30\&.0f"
.br
.ti -1c
.RI "float \fBMaxFollowDistance\fP = 100\&.0f"
.br
.ti -1c
.RI "float \fBMinFollowDistance\fP = 2\&.0f"
.br
.ti -1c
.RI "float \fBElevationAngle\fP = 30\&.0f"
.br
.ti -1c
.RI "float \fBMaxElevationAngle\fP = 85\&.0f"
.br
.ti -1c
.RI "float \fBMinElevationAngle\fP = 0f"
.br
.ti -1c
.RI "float \fBOrbitalAngle\fP = 0f"
.br
.ti -1c
.RI "CameraModes \fBCameraMode\fP = CameraModes\&.Follow"
.br
.ti -1c
.RI "bool \fBMovementSmoothing\fP = true"
.br
.ti -1c
.RI "bool \fBRotationSmoothing\fP = false"
.br
.ti -1c
.RI "float \fBMovementSmoothingValue\fP = 25f"
.br
.ti -1c
.RI "float \fBRotationSmoothingValue\fP = 5\&.0f"
.br
.ti -1c
.RI "float \fBMoveSensitivity\fP = 2\&.0f"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
