.TH "TMPro.Examples.TextMeshProFloatingText" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples.TextMeshProFloatingText
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "IEnumerator \fBDisplayTextMeshProFloatingText\fP ()"
.br
.ti -1c
.RI "IEnumerator \fBDisplayTextMeshFloatingText\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Font \fBTheFont\fP"
.br
.ti -1c
.RI "int \fBSpawnType\fP"
.br
.ti -1c
.RI "bool \fBIsTextObjectScaleStatic\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
