.TH "TMPro.TMP_TextEventHandler.LineSelectionEvent" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_TextEventHandler.LineSelectionEvent
.SH SYNOPSIS
.br
.PP
.PP
Inherits UnityEvent< string, int, int >\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
