.TH "TMPro.Examples.TextMeshSpawner" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples.TextMeshSpawner
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBSpawnType\fP = 0"
.br
.ti -1c
.RI "int \fBNumberOfNPC\fP = 12"
.br
.ti -1c
.RI "Font \fBTheFont\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
