.TH "TMPro.TMP_TextEventHandler" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_TextEventHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, IPointerEnterHandler, and IPointerExitHandler\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCharacterSelectionEvent\fP"
.br
.ti -1c
.RI "class \fBLineSelectionEvent\fP"
.br
.ti -1c
.RI "class \fBLinkSelectionEvent\fP"
.br
.ti -1c
.RI "class \fBSpriteSelectionEvent\fP"
.br
.ti -1c
.RI "class \fBWordSelectionEvent\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPointerEnter\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnPointerExit\fP (PointerEventData eventData)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBCharacterSelectionEvent\fP \fBonCharacterSelection\fP\fC [get, set]\fP"
.br
.RI "Event delegate triggered when pointer is over a character\&. "
.ti -1c
.RI "\fBSpriteSelectionEvent\fP \fBonSpriteSelection\fP\fC [get, set]\fP"
.br
.RI "Event delegate triggered when pointer is over a sprite\&. "
.ti -1c
.RI "\fBWordSelectionEvent\fP \fBonWordSelection\fP\fC [get, set]\fP"
.br
.RI "Event delegate triggered when pointer is over a word\&. "
.ti -1c
.RI "\fBLineSelectionEvent\fP \fBonLineSelection\fP\fC [get, set]\fP"
.br
.RI "Event delegate triggered when pointer is over a line\&. "
.ti -1c
.RI "\fBLinkSelectionEvent\fP \fBonLinkSelection\fP\fC [get, set]\fP"
.br
.RI "Event delegate triggered when pointer is over a link\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
