.TH "TMPro.Examples.TMP_ExampleScript_01" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples.TMP_ExampleScript_01
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBobjectType\fP { \fBTextMeshPro\fP = 0, \fBTextMeshProUGUI\fP = 1 }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "objectType \fBObjectType\fP"
.br
.ti -1c
.RI "bool \fBisStatic\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
