.TH "TMPro.Examples.TMPro_InstructionOverlay" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples.TMPro_InstructionOverlay
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBFpsCounterAnchorPositions\fP { \fBTopLeft\fP, \fBBottomLeft\fP, \fBTopRight\fP, \fBBottomRight\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FpsCounterAnchorPositions \fBAnchorPosition\fP = FpsCounterAnchorPositions\&.BottomLeft"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
