.TH "TMPro.TMP_DigitValidator" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_DigitValidator \- EXample of a Custom Character Input Validator to only allow digits from 0 to 9\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits TMP_InputValidator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override char \fBValidate\fP (ref string text, ref int pos, char ch)"
.br
.in -1c
.SH "Detailed Description"
.PP 
EXample of a Custom Character Input Validator to only allow digits from 0 to 9\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
