.TH "TMPro.Examples.TMP_TextSelector_B" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples.TMP_TextSelector_B
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, IPointerEnterHandler, IPointerExitHandler, IPointerClickHandler, and IPointerUpHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPointerEnter\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnPointerExit\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnPointerClick\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnPointerUp\fP (PointerEventData eventData)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RectTransform \fBTextPopup_Prefab_01\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
