.TH "TMPro.Examples.SkewTextExample" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples.SkewTextExample
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AnimationCurve \fBVertexCurve\fP = new AnimationCurve(new Keyframe(0, 0), new Keyframe(0\&.25f, 2\&.0f), new Keyframe(0\&.5f, 0), new Keyframe(0\&.75f, 2\&.0f), new Keyframe(1, 0f))"
.br
.ti -1c
.RI "float \fBCurveScale\fP = 1\&.0f"
.br
.ti -1c
.RI "float \fBShearAmount\fP = 1\&.0f"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
