.TH "TMPro.Examples" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBenchmark01\fP"
.br
.ti -1c
.RI "class \fBBenchmark01_UGUI\fP"
.br
.ti -1c
.RI "class \fBBenchmark02\fP"
.br
.ti -1c
.RI "class \fBBenchmark03\fP"
.br
.ti -1c
.RI "class \fBBenchmark04\fP"
.br
.ti -1c
.RI "class \fBCameraController\fP"
.br
.ti -1c
.RI "class \fBObjectSpin\fP"
.br
.ti -1c
.RI "class \fBShaderPropAnimator\fP"
.br
.ti -1c
.RI "class \fBSimpleScript\fP"
.br
.ti -1c
.RI "class \fBSkewTextExample\fP"
.br
.ti -1c
.RI "class \fBTeleType\fP"
.br
.ti -1c
.RI "class \fBTextConsoleSimulator\fP"
.br
.ti -1c
.RI "class \fBTextMeshProFloatingText\fP"
.br
.ti -1c
.RI "class \fBTextMeshSpawner\fP"
.br
.ti -1c
.RI "class \fBTMP_ExampleScript_01\fP"
.br
.ti -1c
.RI "class \fBTMP_FrameRateCounter\fP"
.br
.ti -1c
.RI "class \fBTMP_TextEventCheck\fP"
.br
.ti -1c
.RI "class \fBTMP_TextInfoDebugTool\fP"
.br
.ti -1c
.RI "class \fBTMP_TextSelector_A\fP"
.br
.ti -1c
.RI "class \fBTMP_TextSelector_B\fP"
.br
.ti -1c
.RI "class \fBTMP_UiFrameRateCounter\fP"
.br
.ti -1c
.RI "class \fBTMPro_InstructionOverlay\fP"
.br
.ti -1c
.RI "class \fBVertexColorCycler\fP"
.br
.ti -1c
.RI "class \fBVertexJitter\fP"
.br
.ti -1c
.RI "class \fBVertexShakeA\fP"
.br
.ti -1c
.RI "class \fBVertexShakeB\fP"
.br
.ti -1c
.RI "class \fBVertexZoom\fP"
.br
.ti -1c
.RI "class \fBWarpTextExample\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
