.TH "TMPro.Examples.VertexShakeA" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples.VertexShakeA
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBAngleMultiplier\fP = 1\&.0f"
.br
.ti -1c
.RI "float \fBSpeedMultiplier\fP = 1\&.0f"
.br
.ti -1c
.RI "float \fBScaleMultiplier\fP = 1\&.0f"
.br
.ti -1c
.RI "float \fBRotationMultiplier\fP = 1\&.0f"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
