.TH "TMPro.Examples.Benchmark01_UGUI" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples.Benchmark01_UGUI
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBBenchmarkType\fP = 0"
.br
.ti -1c
.RI "Canvas \fBcanvas\fP"
.br
.ti -1c
.RI "TMP_FontAsset \fBTMProFont\fP"
.br
.ti -1c
.RI "Font \fBTextMeshFont\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
