.TH "UIOutlineHexagon" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIOutlineHexagon
.SH SYNOPSIS
.br
.PP
.PP
Inherits MaskableGraphic\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnRectTransformDimensionsChange\fP ()"
.br
.ti -1c
.RI "override void \fBOnPopulateMesh\fP (VertexHelper vh)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override Texture \fBmainTexture\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
