.TH "UnityEngine.SignInWithApple.UserInfo" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.SignInWithApple.UserInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBuserId\fP"
.br
.ti -1c
.RI "string \fBemail\fP"
.br
.ti -1c
.RI "string \fBdisplayName\fP"
.br
.ti -1c
.RI "string \fBidToken\fP"
.br
.ti -1c
.RI "string \fBerror\fP"
.br
.ti -1c
.RI "UserDetectionStatus \fBuserDetectionStatus\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
