.TH "UnityEngine.SignInWithApple" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.SignInWithApple
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCallbackArgs\fP"
.br
.ti -1c
.RI "class \fBSignInWithApple\fP"
.br
.ti -1c
.RI "class \fBSignInWithAppleEvent\fP"
.br
.ti -1c
.RI "struct \fBUserInfo\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBUserDetectionStatus\fP { \fBLikelyReal\fP, \fBUnknown\fP, \fBUnsupported\fP }"
.br
.ti -1c
.RI "enum \fBUserCredentialState\fP { \fBRevoked\fP, \fBAuthorized\fP, \fBNotFound\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
