.TH "UnitySignInWithApple" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitySignInWithApple
.SH SYNOPSIS
.br
.PP
.PP
Inherits NSObject, <ASAuthorizationControllerDelegate>, and <ASAuthorizationControllerPresentationContextProviding>\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "SignInWithAppleCallback \fBloginCallback\fP"
.br
.ti -1c
.RI "CredentialStateCallback \fBcredentialStateCallback\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
