.TH "UnityBuyAppController" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityBuyAppController
.SH SYNOPSIS
.br
.PP
.PP
Inherits UnityAppController\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBshouldResignActive\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
