.TH "UnityEngine.SignInWithApple.CallbackArgs" 3 "Achroma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.SignInWithApple.CallbackArgs
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UserCredentialState \fBcredentialState\fP"
.br
.RI "The state of the user's authorization\&. "
.ti -1c
.RI "\fBUserInfo\fP \fBuserInfo\fP"
.br
.RI "The logged in user info after the call is done\&. "
.ti -1c
.RI "string \fBerror\fP"
.br
.RI "Whether the call ends up with an error\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma from the source code\&.
