.TH "UniWebViewPostBuildProcessor" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UniWebViewPostBuildProcessor
.SH SYNOPSIS
.br
.PP
.PP
Inherits IPostGenerateGradleAndroidProject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPostGenerateGradleAndroidProject\fP (string path)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBcallbackOrder\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
