.TH "UniWebViewGradleConfig" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UniWebViewGradleConfig
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUniWebViewGradleConfig\fP (string filePath)"
.br
.ti -1c
.RI "void \fBSave\fP (string path=null)"
.br
.ti -1c
.RI "string \fBPrint\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBUniWebViewGradleNode\fP \fBROOT\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
