.TH "UniWebViewGradlePropertyPatcher" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UniWebViewGradlePropertyPatcher
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBPatch\fP (string filePath)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
