.TH "UserInfo" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserInfo
.SH SYNOPSIS
.br
.PP
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const char * \fBuserId\fP"
.br
.ti -1c
.RI "const char * \fBemail\fP"
.br
.ti -1c
.RI "const char * \fBdisplayName\fP"
.br
.ti -1c
.RI "const char * \fBidToken\fP"
.br
.ti -1c
.RI "const char * \fBerror\fP"
.br
.ti -1c
.RI "ASUserDetectionStatus \fBuserDetectionStatus\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
