.TH "VibrationController" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VibrationController
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBPop\fP ()"
.br
.ti -1c
.RI "static void \fBPeek\fP ()"
.br
.ti -1c
.RI "static void \fBNope\fP ()"
.br
.ti -1c
.RI "static void \fBLight\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
