.TH "Vibration" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vibration
.SH SYNOPSIS
.br
.PP
.PP
Inherits NSObject\&.
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(BOOL) + \fBhasVibrator\fP"
.br
.ti -1c
.RI "(void) + \fBvibrate\fP"
.br
.ti -1c
.RI "(void) + \fBvibratePeek\fP"
.br
.ti -1c
.RI "(void) + \fBvibratePop\fP"
.br
.ti -1c
.RI "(void) + \fBvibrateNope\fP"
.br
.ti -1c
.RI "(void) + \fBvibrateLight\fP"
.br
.ti -1c
.RI "(static void) + \fBInit\fP"
.br
.ti -1c
.RI "(static void) + \fBVibratePop\fP"
.br
.ti -1c
.RI "(static void) + \fBVibratePeek\fP"
.br
.ti -1c
.RI "(static void) + \fBVibrateNope\fP"
.br
.ti -1c
.RI "(static void) + \fBVibrateLight\fP"
.br
.ti -1c
.RI "(static void) + \fBVibrate\fP"
.br
.ti -1c
.RI "(static void) + \fBVibrate\fP"
.br
.ti -1c
.RI "(static void) + \fBCancel\fP"
.br
.ti -1c
.RI "(static bool) + \fBHasVibrator\fP"
.br
.ti -1c
.RI "(static void) + \fBVibrate\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static int \fBAndroidVersion\fP\fC [get]\fP"
.br
.in -1c
.SH "Method Documentation"
.PP 
.SS "+ (static void) Init "
summary> Tiny pop vibration /summary> 
.SS "+ (static void) Vibrate (long) milliseconds"
summary> Only on Android https://proandroiddev.com/using-vibrate-in-android-b0e3ef5d5e07 /summary> 
.SS "+ (static void) Vibrate (long[]) pattern(int) repeat"
summary> Only on Android /summary> 
.SS "+ (static void) VibrateLight "
summary> Only on Android https://developer.android.com/reference/android/os/Vibrator.html#vibrate(long) /summary> 
.SS "+ (static void) VibrateNope "
summary> 3 small vibrations /summary> 
.SS "+ (static void) VibratePeek "
summary> 3 small vibrations /summary> 
.SS "+ (static void) VibratePop "
summary> Small peek vibration /summary> 

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
