.TH "VibrationExample" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VibrationExample
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTapVibrate\fP ()"
.br
.ti -1c
.RI "void \fBTapVibrateCustom\fP ()"
.br
.ti -1c
.RI "void \fBTapVibratePattern\fP ()"
.br
.ti -1c
.RI "void \fBTapCancelVibrate\fP ()"
.br
.ti -1c
.RI "void \fBTapPopVibrate\fP ()"
.br
.ti -1c
.RI "void \fBTapPeekVibrate\fP ()"
.br
.ti -1c
.RI "void \fBTapNopeVibrate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBinputTime\fP"
.br
.ti -1c
.RI "Text \fBinputPattern\fP"
.br
.ti -1c
.RI "Text \fBinputRepeat\fP"
.br
.ti -1c
.RI "Text \fBtxtAndroidVersion\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
