.TH "WindowsRuntimeExtension" 3 "Achroma Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindowsRuntimeExtension
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Type \fBGetBaseType\fP (this Type type)"
.br
.ti -1c
.RI "static Assembly \fBGetAssembly\fP (this Type type)"
.br
.ti -1c
.RI "static bool \fBIsValueType\fP (this Type type)"
.br
.ti -1c
.RI "static bool \fBIsGenericType\fP (this Type type)"
.br
.ti -1c
.RI "static bool \fBMatchBindingFlags\fP (bool isPublic, bool isPrivate, bool isStatic, BindingFlags bindingAttr, bool baseClass)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Achroma Plugin from the source code\&.
